---
title: "Acknowledgements"
output: html_notebook
---

# Acknowledgements

This project was made possible through partial support provided by U. S. Environmental Protection Agency grants CB-96305701 (Chesapeake Bay Program) and I-98339413 (CWA §106), and by the Interstate Commission on the Potomac River Basin (ICPRB).

The Chessie BIBI index of non-tidal stream health was developed in 2011 in collaboration with biologists from across the Chesapeake Bay watershed. This report presents a refinement of the 2011 index. Technical work was performed by ICPRB staff on an updated database of stream macroinvertebrate data. An adhoc Technical Advisory Group (TAG) was created to guide the process and consisted of benthic macroinvertebrate experts from New York, Pennsylvania, Maryland, Virginia, West Virginia, Delaware, and the District of Columbia as well as federal, academic, and River Basin Commission partners. The authors wish to thank members of the technical advisory group for their guidance and feedback: Alexander J. Smith (NYDEC), Brianna Hutchison (SRBC), Christopher J. Victoria (Ann Arundel Co.), Dan Boward (MDDNR), David Ward (Loudoun Co.), Don Smith (VADEQ), Dustin Shull (PADEP), Elisha S. Rubin (DOEE), Ellen Dickey (DNREC), Ellyn Campbell (SRBC), Ginger Rogers (Versar Inc. for Howard Co.), Greg Pond (USEPA Region 3), Jason Hill (VADEQ), Jeff Bailey (WVDEP), Jennifer St. John (Montgomery Co.), John Wirts (WVDEP), Kelly Maloney (USGS), Mark Secrist (FWS), Michael Whitman (WVDEP), Mike Bilger (Susquehanna University), Mike Kashiwagi (MDDNR), and Richard Mitchell (USEPA). Other members of the Chesapeake Bay Program’s Stream Health Workgroup provided input on final presentation of the results.

The Chessie BIBI could not have been produced without the cooperation of staff of the monitoring programs who responded to our data requests. The long hours and sometimes harsh conditions endured by field crews and the diligence and taxonomic expertise of the laboratory staff are the very solid foundation on which the Chessie BIBI index was built in 2011 and then refined in this study. Contributing monitoring programs are listed in Table 1 of the report. Finally, the authors especially thank Greg Pond (USEPA Region 3), Karen Blocksom (USEPA ORD) and A. J. Smith (NYDEC) for their many insightful comments and suggestions during critical stages of the index refinement; Mike Mallonee (ICPRB-CBPO) for his guidance and help in modifying, populating, and updating the relational database that houses the primary data; and Peter Tango (USGS-CBPO), Scott Phillips (USGS), and Jennifer Greiner (USFWS) for their support and encouragement.