---
title: "Appendix M: Potential Biases in the Regional Index Ratings"
output: html_notebook
---

## Appendix M: Potential Biases in the Regional Index Ratings

Appendix G explored the influence of hydrologic subregion (river basin), physiographic province (Coastal Plain, Piedmont, Valley & Ridge), and Level III ecoregion (Woods et al. 1999, Omernik 2003) on individual stream macroinvertebrate metrics. The results were used to establish the twelve Chesapeake bioregions. A bioregion spatial resolution best serves local stream evaluation and restoration efforts because it accounts for local (bioregion) natural factors that can influence outcomes, such as elevation, slope, latitude, seasonal temperature and precipitation patterns, geology, soils, and land cover. Improvements observed over time with the bioregion-specific indices should be due more to human intervention than to underlying differences in natural features.
Regional indices were also developed for the Chesapeake watershed. These indices represent two large geographical areas (Coast, Inland) which experience wide ranges of one or more environmental features. Thus, they may not be sensitive to features specific to the smaller, more homogenous bioregions. Regional indices were developed because the Chesapeake Bay Program (CBP) wants an indicator of stream health it can apply watershed-wide to track the proportion of stream miles with a rating of Fair or better. The report recommends the family-level regional indices (Coast, Inland) for that purpose. In this appendix, we ask the question “Do natural features substantially influence the narrative ratings produced by the two family-level regional indices?” We expect to find small differences in the region and bioregion index scores that can be traced back to the local influence of specific natural features. We want to know if the narrative ratings, derived from distributions of the scores in least-disturbed (Reference) conditions, are similarly influenced. If the influences are minimal, narrative ratings for both the region and bioregion indices can be considered comparable indicators of stream condition and restoration progress.

### Bioregion

The bioregions capture most of the natural landscape features that can affect macroinvertebrate communities in the Chesapeake Bay watershed. Comparisons of the bioregion and region index narrative ratings should indicate if the natural features accounted for in the bioregion indices are collectively influencing—biasing—the region index ratings. The family-level region index scores and ratings were analyzed by bioregion and compared to their family-level bioregion index counterparts. The family-level Coast index results were subset into their Southeastern Plains (SEP) and Mid-Atlantic Coast (MAC) bioregions. Similarly, the family-level Inland index results were subset into their respective Blue Ridge Mountains (BLUE), Northern Appalachian Platue (NAPU), Northern Central Applachians (NCA), Central Appalachians (CA), Northern Ridge and Valley (NRV), Southern Ridge and Valley (SRV), Southern Great Valley (SGV), Upper Northern Piedmont (UNP), Lower Northern Piedmont (LNP), and Piedmont (PIED) bioregions. Results were further divided into the four standardized condition categories, i.e., Reference, Minimally Degraded, Moderately Degraded, and Degraded.

When parsed by bioregion, the Coast and Inland region index scores show the expected decline as condition category changes from Reference to Degraded (Figure M-1), and the plots are similar to those for the family-level bioregion indices (Figures 12 and 13). A bioregion-related bias would be expected to dramatically alter category distributions of the region index scores relative to each other. This appears to occur in one case, the MAC Reference condition category, but this is mostly likely an artifact of the MAC’s low Reference sample size, i.e. 17. Distributions of the regional index scores in some bioregions do shift up or down in all four condition categories relative to their bioregion counterparts. For example, the Inland index scores in NCA are overall higher than in other bioregions (Figure M-1). They are also higher than the NCA bioregion index scores (Figure 12). In another example, the Inland index scores in UNP and LNP are substantially lower than in other bioregions (Figure M-1). They are also lower than the UNP and LNP bioregion index scores (Figure 13). The differences between these region and bioregion index scores suggest that, in the context of the entire region, conditions in the four condition categories may be of a higher quality in NCA and of a lower quality in UNP and LNP for reasons that are not accounted for by the three water quality and eight stream habitat parameters used to classify streams (see Report Section ii D. Environmental Condition Classification). NCA is sparsely populated and heavily forested while UNP and LNP include the densely populated Baltimore-Washington metropolitan region (Tables H-2 and H-3).

The common scheme for assigning narrative ratings to index scores is intended to circumvent the differences described above to some degree. Each bioregion or region is rated against threshold values corresponding to the 50th, 25th, 10th and ½ of 10th percentile of the index scores in its Reference condition category. A comparison of ratings derived from the region and bioregion indices in the Reference condition category shows mostly good agreement in the frequency of Excellent, Good, and Fair ratings (%EGF) (Table M-1). These three ratings are considered desirable by CBP in achieving its stream health goal. The %EGFs derived from bioregion indices are tightly centered on an average of 86.2% (SD 3.2%). The %EGFs derived from the region indices average nearly the same (85.2%) but show more variability (SD 9.0%). Six of the twelve bioregions show little disagreement between the region and bioregion index ratings (less than +10%). The region indices generate somewhat higher %EGFs than the bioregion index for BLUE (13.4%) and CA (10.7%); they generate somewhat lower %EGFs for MAC (-14.3%), NAPU (-16.3%), NRV (-13.4%), and UNP (-15.4%).

Rating differences in MAC could be discounted because the small Reference sample sizes in these bioregions make the indices less precise (Table M-1). Only MAC data in the Chesapeake watershed were considered in building the indices, which limited the number of Reference sites. The BLUE bioregion index may be less discriminatory because a very small Degraded sample size (n = 7) was used to build the index. In these two bioregions, the region index may prove to be more robust and representative of stream conditions because it is derived from a greater number of Reference samples.

It is not clear from this comparison if natural features in NAPU, NRV, and UNP cause the relatively large differences in the index ratings of these bioregions. Elsewhere, the region and bioregion family-level indices can be expected to generate comparable ratings overall.

_Figure M-1. The family-level Inland and Coast (region) index scores shown by bioregion. Condition categories: Reference (REF), Minimally Disturbed (MIN), Moderately Disturbed (MOD), Degraded (DEG). Sample size (n) of each category is indicated at top. Color gradient identifies narrative ratings for family-level region index: dark green = Excellent; light green = Good; yellow = Fair; orange = Poor; and red = Very Poor._

_Table M-1. Frequency of Excellent, Good, and Fair ratings derived with the region and bioregion indices for Reference (least-disturbed) conditions. Percent change is the difference between the two indices relative to the bioregion index._

### Season

Season can potentially influence index scores and ratings. For example, some insects emerge in spring and become less abundant or less detectable (i.e., early instars) in the summer or fall. The family-level region index scores and ratings were divided into two seasons, March – June (spring and early summer) and July – November (late summer and early fall), and compared. Scores of the Coast and Inland region indices show the expected declining trend from Reference to Degraded in both seasons (Figure M-2). In the Reference category, where anthropengenic impacts are minimized, seasonal distributions of the region and bioregion index scores were not different in eight bioregions (Table M-2). In the heavily sampled LNP, the Wilcoxon test finds the region and bioregion scores are different (p<0.01); however, %EGFs differ by only 9.9%. The MAC bioregion within the Chesapeake watershed has insufficient samples. The NAPU and UNP bioregions show the largest differences in region index scores and %EGF ratings.
The relatively small differences between most region and bioregion %EGFs suggest season does not bias the region index ratings. Differences in NAPU and UNP may be due to seasonal changes but more likely this reflects agency bias.

_Figure M-2. Distributions of family-level Inland and Coast (region) index scores, by season: March – June and July – November. Condition categories: Reference (REF), Minimally Disturbed (MIN), Moderately Disturbed (MOD), Degraded (DEG). Sample size (n) of each category is indicated at top. Color gradient identifies narrative ratings for family-level region index: dark green = Excellent; light green = Good; yellow = Fair; orange = Poor; and red = Very Poor._

_Table M-2. Percent of Excellent, Good, and Fair ratings (%EGF) in Reference conditions, for the Coast and Inland region indices. Wilcoxon test p-values <0.01 are shown. * Average and StDev exclude MAC._

### Karst

Karst geology could potentially alter benthic macroinvertebrate community composition. Therefore, areas with karst geology might benefit from a modified index or an independent index constructed specifically for assessing areas with karst. The Coast region did not contain any karst, and is excluded from this comparison. The Inland region was divided into sampling events collected at sites without karst geology (Non-Karst) and sites with karst geology (Karst). The two types were further divided into the four condition categories and plotted against the Inland index scores (Figure M-2).

_Figure M-3. Inland family-level index scores were divided into areas with and without karst geology. The box-and-whisker plots depict the trend in scores from Reference (REF) to Degraded (DEG) for each subset of data. The numbers at the top of the plots indicate the sample size (n) of each environmental class. The color gradient behind the box plots identifies the range of each rating category defined using all the applicable data for a region. Narrative ratings for family-level region index: dark green = Excellent; light green = Good; yellow = Fair; orange = Poor; and red = Very Poor._

We also compared region index scores and ratings (%EGF) in the karst-dominated SGV bioregion and the neighboring SRV bioregion which has karst intrusions but is dominated by shale, sandstone, and other non-calcareous rock. The region (Inland) index scores in Reference conditions do not differ in the two bioregions (p < 0.01). Average scores are 86.7 in SGV and 88.6 in SRV. The %EGFs are also close, with 86.6% in SGV and 90.4% in SRV (Table M-1).

Karst geology does not affect the Inland family-level index. The results agree with another analysis which found many of the macroinvertebrate metrics considered in building the indices insensitive to karst (Table G-3, karst vs. no karst SRV* and karst vs. no karst SGV). This is not to say karst does not influence individual macroinvertebrate taxa. Only that the metrics selected for the bioregion and region family-level indices (Tables 9 and 15) apparently do not respond strongly to karst.

### Monitoring Program

We noticed three montoring programs stood out as having much lower than expected region index %EGF in Reference conditions: Loudon County Steam Quality Assessment Program (LC-DBD_LCSAP), Montgomery County Stream Monitoring Program (MC-SPS_MCSMP), and New York Statewide Monitoring Program (NYDEC_RSMP) (Table M-3). Each provided data with sites that appeared to meet the three water quality and eight habitat criteria for Reference condition (II. Methods D. Environmental Condition Classification).

_Table M-3. Percent of Excellent, Good, and Fair ratings (%EGF) of the Coast and Inland region indices for sites in Reference conditions, by monitoring program. Percentages for sample sizes <10 not considered._

We prepared the analysis data set by including only samples collected with a kick-net or similar procedure, excluding taxa counted by only a few programs, rarefying counts, and standardizing taxonomic attributes (II. Methods. B. Taxonomic Preparation). Therefore, the bias related to field sampling methods or laboratory enumeration methods have been reduced. We suspect differences in Table M-3 may be related to how agency staff evaluate one or several of the stream habitat parameters we used to classify sites, namely bank stability, bank vegetation, channel alteration, embeddedness, epifaunal substrate, flow, riffle/run/pool ratio, and sedimentation. The results suggest scoring is less stringent or somehow different in at least these three programs compared to other programs. This would explain the programs’ lower %EGF at what are technically least-disturbed, or Reference, sites. We have no way to verify the comparability of agency habitat scores for these eight parameters and take them as submitted.

The NAPU bioregion index has been flagged as problematic in the report. Distributions of its order-, family-, and genus-level bioregion index scores in Reference and Degraded conditions are poorly separated (Figures 11, 13, and 15), causing the index to have a poor classification efficiency for each taxonomic version of the bioregion index (Table 14). NYDEC_RSMP samples comprise 16 (18%) of the 89 Reference sites used to develop the NAPU bioregion indices, thus their impact on index score distributions in Reference and NAPU scoring thresholds is potentially large. Most of LC-DBD_LCSAP and MC-SPS_MCSMP samples that met our Reference criteria were collected in the LNP and UNP bioregion. Although their samples comprise less of their respective Reference pools, they still impacted the LNP and UNP bioregion indices. Less obvious differences in how other programs score habitat conditions may affect additional bioregion indices, given the relatively large differences seen in CA, NRV, and PIED in Tables M-1 and M-2.

### Conclusions

The natural features collectively represented by bioregion do not appear to substantially change the narrative ratings of the two family-level region indices relative to the twelve family-level bioregion indices. Most bioregions showed less than +10% change in %EGF between region and bioregion index ratings. NAPU shows the greatest change in %EGF (-16.3%) followed by UNP (-15.4%). Rating differences are also less than +10% in most of bioregions when scores and ratings of the region indices are compared by season and karst. Only LNP, UNP, and NAPU show seasonal differences in %EGF greater than +10%. These results corroborate direct comparisons of individual ratings which show less than 10% disagreement between the bioregion and region family-level index ratings (Table 20A). Overall, we believe the differences are not large enough to dissuade use of the family-level region indices.

We suspect differences in the criteria used by some monitoring programs to score habitat parameters effectively bias the bioregion indices, and cause the large differences observed between bioregion and region indices in some bioregions. Sites that are scored differently or less stringently can diminish the overall quality of sites in the Reference category. One of the most important aspects of IBI development is the classification of Reference and Degraded conditions. Environmental condition classification influences metric selection, metric scoring, and sensitivity of the final index. Standard evaluation procedures for a common suite of habitat parameters performed by all monitoring programs would make it easier for the programs to collaborate, review, verify previous conclusions, and rapidly improve the science.


