---
title: "Appendix G: Stream Classification"
output: html_notebook
---

## Appendix G: Stream Classification

Classifying and analyzing streams according to natural features in the environment reduces variability in the data analysis caused by the natural features and more clearly reveals stream responses to anthropogenic disturbance. We explored the natural differences in taxonomic assemblages of stream macroinvertebrates across the Chesapeake drainage area and identified possible ‘bioregions’ that support communities with distinct differences. Hydrology, physiography, and ecoregion (Figure G-1) are three environmental factors governing the natural landscape of the Chesapeake Bay drainage area. These three factors were used to identify and delineate bioregions.

_Figure G-1. Maps showing the four HUC4 hydrologic subregions of the Chesapeake Bay drainage area overlaying Physiographic Provinces (left) and Level III Ecoregions (right). Ecoregion abbreviations: 45 PIED, Piedmont; 60 NAPU, Northern Appalachian Plateau and Uplands; 62 NCA, North Central Appalachians; 63 MAC, Middle Atlantic Coastal Plain; 64 NPIED, Northern Piedmont; 65 SEP, Southeastern Plains; 66 BR, Blue Ridge; 67 R&V, Ridge and Valley; and 69 CA, Central Appalachians. Small portions of 58 NEH (Northeastern Highlands) and 83 EGLHL (Eastern Great Lakes and Hudson Lowlands) were included with 60 NAPU in the analyses._

The analysis was limited to the months of March through June because most monitoring programs collect samples at this time (Figure 1). We assumed that regional differences found in this spring and early summer period would be echoed in late summer and autumn (July – November). The analysis also was limited to 1st to 4th order streams to minimize the potential effect of stream size on biological metrics. Only biological data from comparatively undisturbed sites were used in the analysis in order to minimize the confounding effects of anthropogenic disturbances. Undisturbed sites were defined as follows in all but two ecoregions:

    Habitat – at each sampling site, fewer than four of the eight metrics below are allowed to be (blank), all habitat scores have to be > 10 or (blank), and the average of the scores (excluding (blanks)) has to be > 16.
    BANKS
    Bank Stability
    BANKV
    Bank Vegetation
    CH_ALT
    Channel Alteration
    EMBED
    Embeddedness
    EPI_SUB
    Epifaunal Substrate
    FLOW
    Flow Status
    RIFF
    Riffle/Run/Pool Ratio
    SED
    Sedimentation
    Water Quality – at least one parameter must have a measurement
    SPCOND*
        Specific Conductivity
        < 300 μmhos/cm or (blank)
    PH
        pH
        5 < pH < 9 or (blank)
    DO**
        Dissolved Oxygen
        > 5.0 mg/liter or (blank)
        
* values less than 25 converted to (blank)
** values greater than 25 converted to (blank)

In the Mid-Atlantic Coast (MAC) and Southeastern Plain (SEP) ecoregions, different stream habitat parameters were typically collected by the three major monitoring agencies there: Delaware Department of Natural Resources and Environmental Control (DNREC), Virginia Department of Environmental Quality (VADEQ), and Maryland Department of Natural Resources (MDDNR). We considered the scores for the following nine habitat metrics if they were recorded in the MAC ecoregion: BANKS, BANKV, CH_ALT, EPI_SUB, shading (SHAD), aesthetics (AESTH), pool/glide quality (POOL), riparian vegetation zone width (RIP_ZONE), and instream habitat (INSTR). We considered these same nine metrics as well as EMBED, riffle (RIFF), velocity-depth combinations (VEL_D) in the SEP ecoregion if they were recorded. For a site to qualify as undisturbed, all the non-blank habitat scores had to be > 10 and the average score > 16. The sites also had to meet the water quality criteria above.

### Statistical Methods

We performed both univariate and multivariate analyses using the vegan (Oksanen et al. 2016) and rpart (Therneau et al. 2015) packages available for R Statistical Software. The Bray-Curtis Dissimilarity Index was used to compare within group and between group variability based on benthic macroinvertebrate composition using the vegan package. This index compares the relative abundance of each taxon in a sample to that of another sample. HUC4’s and Level III Ecoregions were used to group the data prior to comparisons. Values range between 0 and 1 representing samples with the exact same composition/abundance and samples which do not share any compositional similarities, respectively. The mean variability from the Bray-Curtis Dissimilarity Index, within and between groups, was plotted as a dendrogram to visually interpret the relationship among groups of interest.

Another univariate test was performed using Multi-Response Permutation Procedures (MRPP). MRPP is a nonparametric test that utilizes a distance measure, in this case Bray-Curtis Dissimilarity, to test if within-group variability is less than would be expected by chance for a set of predefined groups. McCune et al. (2002) indicate that the chance-corrected within-group agreement (A) must be interpreted along with the p-value because large sample sizes will often result in a significant p-value but may poorly represent within group homogeneity. A-values close to zero indicate that within-group variance is not explained well by the predefined groups, and thus cannot be discerned from within-group variance expected by chance. The vegan package was used to test MRPP on each environmental factor independently (i.e., Subregion, Basin, Level III Ecoregions, Month, Mean HUC12 Elevation, Mean HUC12 Slope, Latitude, Strahler Stream Order).

The vegan package also provides a method for assessing beta-diversity using the Bray-Curtis Dissimilarity Index, called betadisper (Oksanen et al. 2016). Beta-diversity is a measure of the similarity between two observed assemblages. Bray-Curtis Dissimilarity was used to find the mean within-group variability, distance from the group’s median spatial distance, for each pre-defined group (e.g., HUC4 or Level III Ecoregions). This function only provides within-group variability and does not test for between-group variability. An ANOVA with a post-hoc Tukey HSD test was performed pairwise for each predefined group using the mean within-group variability provided by the betadisper function. Comparing within-group variability provides a coarse assessment of similarity between different designated regions; if variability (beta-diversity) is similar between two regions it may be appropriate to join the two regions. However, this must be interpreted with caution because two groups may be considered statistically similar, due to similar within-group variability, but the assemblages may differ completely.

A Recursive Partitioning and Regression Tree (RPART) analysis (Therneau et al. 2015) was used to assess the relative influence of multiple environmental factors on a suite of seventeeen macroinvertebrate metrics. RPART is a nonparametric test that allows for multivariate comparisons. Six compositional metrics (% Non-Insect, % Chironomidae, % EPT, % Ephemeroptera, % Plecoptera, and % Trichoptera), six functional feeding group metrics (% Collectors, % Gatherers, % Filter Feeders, % Predators, % Shredders, and % Scrapers), and five habit metrics (% Burrowers, % Clingers, % Climbers, % Sprawlers, and % Swimmers) were individually assessed with the RPART analysis using four environmental variables (i.e., bioregions, watershed mean slope, watershed mean elevation, and Strahler stream order). This analysis produced a classification tree that aggregates the data into progressively similar groups based on the provided environmental variables.

Finally, sites in the Ridge and Valley (67) ecoregion were used to investigate the potential influence of surficial karst geology on stream macroinvertebrates. The ‘Great Appalachian Valley,’ a broad trough of valley lowlands stretching from Quebec to Alabama, forms the ecoregion’s eastern side. It is a broad, relatively flat area underlain by carbonate (limestone and dolomite) bedrock. The western side of the ecoregion consists of shale and sandstone ridges and narrow, carbonate valleys. We used Kruskal-Wallis to examine differences presumably associated with karst geology.

### Hydrologic Units and Physiographic Regions

The Chesapeake drainage area is 491 miles (790 km) on its longest, northeast-southwest axis and covers 64,000 square miles (165,759 square kilometers). Earlier efforts (Buchanan et al. 2011) suggested combinations of Level III Ecoregions are strong explanatory variables in the Chesapeake drainage and useful in classifying stream macroinvertebrate communities. Exploratory RPART analyses with the current data set suggested a latitudinal change in undisturbed communities may occur around 39oN – 40oN in the Appalachian Highlands region, possibly at the Susquehanna-Potomac river basin boundary. For this study, we first tested the relative importance of hydrologic subregions and physiographic region and then examined the usefulness of ecoregions in stream classification.
Figure G-2 shows Bray-Curtis Dissimilarity Index p-values for assemblages in the three major hydrologic subregions (HUC4) of the Chesapeake region: Susquehanna (0205), Potomac (0207), and the Lower Chesapeake-James (0208). The three subregions differed from each other to varying degrees, with Susquehanna showing the strongest separation. This may be due to the history of glaciation in the Susquehanna, or to seasonal temperature, precipitation, and other climatic differences between north and south. Between-group differences for Potomac and Lower Chesapeake-James subregions are relatively weak (p = 0.111). Both subregions are primarily in the Appalachian Highland; however, the Potomac landscape is dominated by the Ridges and Valleys Province whereas the Lower Chesapeake-James landscape is dominated by the Piedmont Province.

We expanded the analysis to include the small Upper Chesapeake subregion (0206) located downstream of the Susquehanna subregion (Figure G-1). The low salinity portion of Chesapeake Bay is the major hydrologic feature of this subregion and freshwater flow from the Susquehanna River far out-weighs contributions from the subregion’s other non-tidal streams and rivers. Taxonomic variability in the Upper Chesapeake subregion proves somewhat similar to that in the larger Susquehanna subregion (0205); it differs from taxonomic variability found in the Lower Chesapeake-James and the Potomac (Figure G-3). The Susquehanna subregion continues to differ strongly from the Lower Chesapeake and Potomac subregions (p < 0.001), and the Potomac and Lower Chesapeake-James are still weakly different (p = 0.187). An argument can be made that the Upper Chesapeake subregion encompasses a drowned portion of the Susquehanna River, which makes connectivity between streams in Susquehanna and Upper Chesapeake subregions higher than connectivity between these subregions and the Potomac or lower Chesapeake. Hence, one could expect variability in the Susquehanna and Upper Chesapeake to be more similar, regardless of differences in their physiographic composition.

The Upper Chesapeake, Potomac, and Lower Chesapeake-James HUC4’s overlap the Coastal Plain physiographic region. If we remove Coastal Plain from the hydrology-based analysis above, we can get a measure of the relative influence of this physiographic region. When Coastal Plain sites were excluded, the within-group and between-group dissimilarity index values dropped slightly in the three major HUC4’s (Figure G-4). Taxonomic variability in the Susquehanna subregion and truncated Upper Chesapeake subregions became very similar (p = 0.977). Here, the Upper Chesapeake includes only samples from the Piedmont Province. Differences between the Upper Chesapeake, Potomac, and Lower Chesapeake-James subregions strengthened, although the difference between the latter two still is weak (p = 0.067). Physiographic regions appear to play a role in structuring macroinvertebrate communities within large hydrologic units. This argument has been made by Omernik (2003), Pond et al. (2011), and others.

The results suggest two major stream classifications could be applied to reduce the natural variability of stream macroinvertebrate assemblages in the Chesapeake drainage basin: a north-south division, probably at the Susquehanna-Potomac boundary, and an east-west division at the Coastal Plain and Piedmont boundary.

### Level III Ecoregions

We used Level III Ecoregions to explore the usefulness of the suggested north-south and east-west divisions. Level III Ecoregions are sub-sections of the physiographic provinces. The Valley and Ridge physiographic province is a relatively large province that crosses the length of the Chesapeake drainage. It is equivalent to the long, heterogeneous Ridge and Valley (R&V) Level III Ecoregion in the Chesapeake drainage (Figure G-1). The Piedmont province is technically divided into Northern Piedmont (64) and Piedmont (45) ecoregions; however, the Northern Piedmont (64) ecoregion stretches across the Potomac-Susquehanna boundary, which makes it difficult to assign it to the northern or southern tier of the Chesapeake drainage. The Central Appalachian (69) ecoregion, a minor component of the Appalachian Highland region in the Chesapeake drainage area, is found in three relatively small areas: two in the northern Susquehanna subregion and one in the southern Potomac subregion. The remaining physiographic provinces in the Chesapeake drainage are confined to the north or south. The Appalachian Plateau province, consisting primarily of the Northern Appalachian Plateau and Upland (NAPU, 60) and North Central Appalachian (NCA, 62) ecoregions, is confined to the north. The Piedmont (45) ecoregion lies wholly in the southern tier. The thin Blue Ridge province (Level III Ecoregion 66) parallels the eastern side of the Valley and Ridge province and is located almost entirely in the southern tier. The Coastal Plain province, consisting of the Southeastern Plains (SEP, 63) and Mid-Atlantic Coastal Plain (MAC, 65) ecoregions in the Chesapeake, is confined to the southeast.
To further explore north-south differences, we divided the large Ridge and Valley Level III Ecoregion into northern (67N) and southern (67S) components at the Susquehanna-Potomac boundary. We divided the Northern Piedmont (64) Level III Ecoregion into a northern component (64N) contained in the Susquehanna (0205) and Upper Chesapeake (0206) HUC4 subregions and a southern component (64S) contained in the Potomac (0207) and Lower Chesapeake-James (0208) HUC4 subregions. Finally, adequate numbers of undisturbed sites allowed us to split the small Central Appalachian (69) segments in the Susquehanna subregion into an upper group (69N) and the small segment in the Potomac into a lower group (69S).

We compared taxonomic variability between and within these twelve possible ecoregion-based groups, focusing individually on the Coastal Plain, the northern tier, and the southern tier of the Chesapeake Bay drainage to minimize noise. The Coastal Plain analysis compared the SEP (65) and MAC (63) Level III Ecoregions. The northern tier analysis consisted of the NAPU (60), NCA (62), Northern R&V (67N), Upper Northern Piedmont (64N), and Upper Central Appalachians (69N) groups. The southern tier analysis consisted of the Southern R&V (67S), Lower Northern Piedmont (64S), Lower Central Appalachians (69S), Piedmont (45), and Blue Ridge (66). P-values were again generated using the vegan function betadisper with a Bray-Curtis Dissimilarity Index and used to compare beta diversity (variability) in undisturbed stream macroinvertebrate assemblages. We found differences between many ecoregions (low p-values), indicating the ecoregion classification approach can be an effective method of further “blocking” the data and reducing noise due to natural environmental factors.

The north-south difference in taxonomic variability was very strong between the two new Ridge and Valley (67) groups (p < 0.001). Taxonomic variability new Upper Northern Piedmont (64N) and Lower Northern Piedmont (64S) regions also differed strongly (p = 0.015). These results justify the proposed north-south division of these two Level III ecoregions at the Susquehanna border. Variability in the Coastal Plain’s MAC (63) Level III Ecoregion differed from all the other ecoregions in the southern tier (p < 0.001). Strong differences were expected in this relatively isolated Chesapeake region, which is mostly separated from the others by Chesapeake Bay. Taxonomic variability in the Coastal Plain’s SEP (65) Level III Ecoregion is in fact like that in the adjacent Piedmont (45) ecoregion (p = 0.990). However, the Coastal Plain ecoregions are bound on the west by the Atlantic Seaboard Fall-Line and their geologies, elevations, and stream gradients differ substantially from those in the Piedmont. These differences were expected to affect stream macroinvertebrate assemblages and SEP (65) was maintained as a distinct bioregion.

In the northern tier of the Chesapeake drainage (Figure G-5), taxonomic variability in the two relatively small Upper Central Appalachian (69N) areas on the western side of the Susquehanna HUC4 is weakly like variability in both NAPU (60) and NCA (62). Variability in the NAPU (60) and NCA (62) ecoregions is very similar (p = 1.000) and values of their dissimilarity indices (within-group variability) are close. NYDEC and PADEQ consider the assemblages in these two ecoregions to be indistinguishable (Chalfant 2009, Smith 2016). The new Northern R&V (67N) group cuts diagonally across the northern tier, separating the Upper Central Appalachian (69N), NCA (62), and NAPU (60) in the north and west from the new Upper Northern Piedmont (64N) group in the southeast corner of the tier. Taxonomic variability in the Northern R&V (67N) does not differ from the other groups. However, variability in the geographically separate Upper Northern Piedmont (64N) groups does differ from the three northern and western groups (p < 0.05). Within-group variability is highest in the Upper Northern Piedmont (64N) group. This probably reflects the area’s more complex landscape, which consists of four of the smaller Level IV Ecoregions: Triassic Lowlands (64a), Diabase and Conglomerate Uplands (64b), Piedmont Uplands (64c), and Piedmont Limestone/Dolomite Lowlands (64d).

In the southern tier of the Chesapeake drainage, within-group values of the Bray-Curtis Dissimilarity Index fall in a tight range between 0.62 and 0.69 (Figure G-6). There are no strong differences between the five groups; the relatively high index values suggest large amounts of with-in group variability. The small Lower Central Appalachian (69S) group splits off first in the dendrogram suggesting its composition is most different from the others. Despite comparable amounts of taxonomic variability, we thought differences in the geographies of the southern tier groups could influence assemblages. For example, elevations are higher, temperatures cooler, and stream gradients steeper in the Blue Ridge (66) compared to the neighboring Piedmont (45) region (Woods et al. 1999). The ridges in the Blue Ridge (66) are geographically separated from ridges in the Southern Ridge and Valley (67S) region by the Great Appalachian Valley. We kept the regions apart pending further comparisons.

### Responses of Individual Biological Metrics to Stream Classes

Analysis of the stream macroinvertebrate assemblages by hydrologic unit, physiographic province, and ecoregion yielded the twelve possible bioregions listed in Table G-1. These bioregions are intended to address some of the inherent macroinvertebrate variability due to latitude, hydrologic connectivity, and large-scale, ecoregion-specific features such as climate, geology, and physiography. The stream gradient classes (very low, low, moderate, and steep) and range of elevations associated with ecoregions, however, may not be adequate to address local effects of slope and elevation on macroinvertebrate communities. Nor will ecoregion address the potential effect of Strahler stream order on specific taxa (e.g., Shredders).

_Table G-1. The twelve bioregions tested in the RPART analysis presented in this appendix._

A Recursive Partitioning and Regression Tree (RPART) analysis was performed on undisturbed assemblages in the two possible bioregions (Table G-1) to explore how well bioregion compared to elevation, slope, and Strahler stream order as an explanatory variable. Seventeen macroinvertebrate metrics representing different habits, feeding guilds, and taxa groups were analyzed with the following algorithm:

    [biological metric] ~ bioregion + mean elevation + mean slope + Strahler order
    
Mean elevation and mean slope of the HUC12 catchments associated with each sampling location were extracted from the USEPA Recovery Screening Tool database (see Appendix H). The stream Strahler order of each sampling location was assigned by overlaying the sample location on the NHDPlus version 1 Medium resolution 100k scale (accessed 1/31/2004) stream layer in ArcGIS 10. QA/QC was performed by comparing the stream names of the NHDPlus version 1 stream to the stream name reported by the sample’s data provider.

Table G-2 provides the RPART results for undisturbed sites in the twelve bioregions. Bioregion was the first or second variable to split the regression tree for all seventeen stream macroinvertebrate metrics, indicating its strong overall influence. The relative importance of bioregion as an explanatory variable ranged from 26% to 53% when compared against elevation, slope and Strahler order. Relative importance considers the variability explained throughout the RPART tree by each explanatory parameter. Bioregion’s relative importance was more than 40% for burrowers, swimmers, filterers, gatherers, Chironomidae, and Trichoptera. It shared roughly equal importance with Strahler stream order and/or slope for Plecoptera and shredders, and with elevation for Ephemeroptera, Trichoptera, and clingers. Its importance was lower than elevation and/or slope for climbers, sprawlers, and non-insects. Classifying streams by bioregion will remove a substantial amount of noise in the data but local factors need to be accounted for when evaluating and scoring the various stream macroinvertebrate metrics.

A final analysis was performed to examine the potential influence of surficial karst geology on stream macroinvertebrate communities. Karst geology is a prominent feature of the Great Appalachian Valley which cuts across the Chesapeake Bay drainage area from northeast to southwest (Figure G-7). The Valley is relatively flat and has the lowest stream density and largest contiguous area of surface karst geology in the Chesapeake drainage. The Blue Ridge bioregion borders it on the east and a chain of mountain ridges, including North Mountain and Great North Mountain, borders it on the west. Again, only assemblages from undisturbed, 1st-4th order streams sampled in spring and early summer were considered. We focused on the Southern Ridge and Valley (67S) bioregion which has the largest proportion of karst geology. The Great Appalachian Valley intersects about a third of this bioregion. We separated sites in the Great Appalachian Valley (SGV) and the remaining Southern Ridge and Valley (67S*) bioregion, and identified sampling sites as karst or no-karst in each based on Weary and Doctor’s (2014) Karst GIS layer. Karst regions were defined by areas with “Karst_Type” represented by the category “Carbonate rocks at or near the land surface in a humid climate;” additionally, “RockType1”and/or “RockType2” from the map layer had to represent limestone, dolomite, or marble. This 2 x 2 analysis was limited by the fact that only 5 undisturbed sites occur on no-karst geology in the Great Valley.

In the Southern Ridge and Valley region not included in the Great Appalachian Valley (67S*), comparisons between karst (n = 69) and no-karst (n = 225) surficial geology at undisturbed sites identified only four of the 17 biological metrics with substantial differences (p<0.05): climbers, Ephemeroptera, EPT, and filterers. This suggests stream macroinvertebrates were not primarily responsive to karst geology. We next compared karst sites in the Great Valley (SGV) and karst sites in the Southern Ridge and Valley (67S*) to determine if our biological metrics respond to the different topographies of these two karst landscapes. Ten of the 17 biological metrics showed significant differences (Table G-3). They included climbers and Ephemeroptera but not EPT or filterers. Topographic differences in the two karst landscapes were apparently more important than karst in differentiating the stream macroinvertebrate assemblages. This conclusion is somewhat confirmed by the absence of significant differences in the SGV karst versus no-karst comparisons, although these comparisons are tenuous due to the low number of no-karst sites. Non-karst factors would include stream order, elevation and/or slope.

We decided to subdivide the proposed Southern Ridge and Valley (67S) bioregion based on the biological differences evident in SGV and SRV (67S*). We recognize some differences may prove to be due to karst while others appear related to topography. Regardless of the cause(s), we feel the taxonomic differences were strong enough to warrant subdividing the region.

Distributions of the seventeen biological metrics in each of the now thirteen possible bioregions were compared and visually examined (Figure G-8 a-q) to confirm the relevance of bioregion in classifying stream macroinvertebrate assemblages. A fair amount of variability is evident in the metric distributions, which suggests macroinvertebrate populations in streams undisturbed by anthropogenic activity are responsive to multiple natural factors, some of which are accounted for in the bioregion assignments and others which are not. Strong differences are evident between the coastal and non-coastal bioregions. Differences between the northern and southern tiers of the non-coastal bioregions are not as strong but still apparent.

In one final decision, we decided to combine the proposed upper and lower Central Appalachian bioregions overlapping the Chesapeake Bay drainage area. Individually, the number of Reference sites in the upper (n=35) and lower (n=24) regions were uncomfortably small. Also, additional Bray-Curtis Dissimilarity Index results and the distributions of many biological metrics (Figure G-8) suggested there was minimal difference in the assemblages of the two regions.

A map and the full names and descriptions of the final twelve bioregions are given in the report (Figure 3 and Table 4).

_Table G-2. Recursive Partitioning and Regression Tree (RPART) analysis results identifying the most important environmental variables explaining variation in stream macroinvertebrate assemblages from undisturbed sites in the Chesapeake drainage area. Formula: [Biological Metric] ~ Bioregion + Watershed Slope + Watershed Elevation + Strahler Order, method = “anova.” X, regression tree primary split; *, regression tree secondary split(s); %, variable importance determined by RPART program1. Variable(s) with the highest importance are indicated. See text for details._

_Table G-3. Comparisons of seventeen macroinvertebrate metrics in karst and non-karst areas. The analysis focuses on the Southern Ridge and Valley (67S) bioregion which has the largest proportion of karst geology in the Chesapeake Bay drainage area. The Southern Ridge and Valley (67S) bioregion is divided into the Great Appalachian Valley (SGV) and the remaining Southern Ridge and Valley (SRV*). Bolded p-values are less than 0.05._

_Figure G-2. Comparison of undisturbed stream macroinvertebrate communities in the Susquehanna, Potomac, and Lower Chesapeake-James HUC4 hydrologic subregions. The Bray-Curtis Dissimilarity Index was calculated for the macroinvertebrate assemblages in each spatial group (each HUC4 in this instance) and the mean within-group distances from each group’s spatial median was compared pairwise using an ANOVA and a post hoc Tukey HSD test. The values in the first table are the p-values from the Tukey HSD test. High p-values indicate that variability in the assemblages is similar between spatial units but does not necessarily indicate that taxa composition is similar. The second table lists the sample sizes of each spatial unit. For the dendrogram, both within- and between-group dissimilarities are calculated with the Bray-Curtis Dissimilarity Index. The dendrogram is plotted using the means of both. The nodes indicate between-group mean dissimilarity and the leaves of the dendrogram indicate within-group dissimilarity. The reversed leaves indicate that within-group dissimilarity was greater than between-group dissimilarity. In the example above, dissimilarity between the Potomac and Susquehanna groups was 0.63 and dissimilarity within the Potomac group was somewhat higher, at 0.65._

_Figure G-3. Comparison of undisturbed stream macroinvertebrate communities in the Susquehanna, Potomac, and Lower Chesapeake-James HUC4 hydrologic subregions. See Figure G-2 heading for details._

_Figure G-4. Comparison of undisturbed stream macroinvertebrate communities in the Susquehanna, Potomac, Upper Chesapeake, and Lower Chesapeake-James HUC4 hydrologic subregions with those portions in the Coastal Plain physiographic province removed. See Figure G-2 heading for details._

_Figure G-5. Comparison of undisturbed stream macroinvertebrate communities in Level III Ecoregions of the Chesapeake drainage northern tier. See Figure G-2 heading for details._

_Figure G-6. Comparison of undisturbed stream macroinvertebrate communities in Level III Ecoregions of the Chesapeake drainage southern tier. See Figure G-2 heading for details. *_

_Figure G-7. Extent of the Great Appalachian Valley in the Chesapeake Bay drainage area._

_Figure G-8 a-q. Distributions of the values of seventeen macroinvertebrate metrics in undisturbed (Reference) conditions across the thirteen possible bioregions identified in this appendix. In each graph, the northern tier bioregions are grouped on the left, the southern bioregions grouped in the middle, and the coastal bioregions grouped on the right. See Table G-1 for bioregion descriptions. Note that SRV in these graphs is equivalent to 67S*, or that portion of the Southern Ridge and Valley that does not include the Great Appalachian Valley. Whiskers of the distributions indicate the 5%ile and 95%ile._




