---
title: "Appendix J: Scoring Methodologies"
output: html_notebook
---

### Appendix J: Scoring Methodologies

To develop an Index of Biotic Integrity (IBI), biological metrics sensitive to a defined disturbance gradient are used to create a single index representing stream biological condition. Many metric values are not directly comparable and must be standardized, or scored, prior to including them in the index. A variety of methodologies are available for scoring metrics. Biological metrics can be scored using continuous or discrete scoring methodologies. Discrete scoring methodologies aggregate a range of data into distinct groups. Traditionally, the discrete groups are scored 1, 3, and 5. Continuous scoring methodologies transform the metric values to a standardized continuous scale – usually a continuous scale from 0 – 100.

An in-depth assessment of three discrete and three continuous scoring methodologies was reported by Blocksom (2003). Blocksom found a continuous scoring method, referred to as CAU, was the most robust for the Mid-Atlantic Highlands Assessment (MAHA) dataset. The CAU method uses the 95th percentile of all the samples to establish the ceiling of the scoring scale and 0 to establish the floor. (For metrics that increase with disturbance, the ceiling is the 5th percentile and the maximum possible value is the floor.) From this point on, this scoring scheme will be referred to as the CAU scoring method to remain consistent with Blocksom’s (2003) terminology. Another common continuous scoring methodology called the All Gradient method (ALL GRAD) is similar to the CAU method but uses the minimum and maximum value of all the data to establish the floor and ceiling of the scoring scale. A third continuous scoring method (REF GRAD) uses the minimum and maximum values of the Reference values only to establish the floor and ceiling of the scoring scale. In this appendix, these three methods are compared to the continuous scoring method used to score metrics for the Chessie BIBI.

### Best Separation Point

The Chessie BIBI scoring methodology, called the Balanced Discrimination Efficiency method, was a modification of an approach described in Buchanan et al. (2011). It finds the threshold at which the percentage of Reference and Degraded samples correctly identified are approximately equal. During assessments of metric sensitivity, an iterative process is used to assess each Reference distribution percentile as a potential threshold for separating Reference and Degraded distributions (Report Section II.F. Metric Testing). This threshold is the Best Separation Point (BSP) and is more specific than the arbitrary threshold of the 25th or 75th percentile of Reference values that is often used (see for example Figure 4 in the report). The BSP was used to identify the midpoint on the 0 – 100 metric scoring scale (Report Section II.G. Metric Scoring Approach). Including the BSP, along with floor and ceiling thresholds, in the scoring procedure improves the interpretability of the results because the BSP represents the point that equally separates the expected Reference and Degraded distributions. Therefore, this scheme identifies the poorest biological condition (values less than the floor), the best biological condition (values greater than or equal to the ceiling), and the point of greatest uncertainty in biological condition (BSP).

Scoring methodologies such as CAU can provide scores like those derived with the BSP when the Reference and Degraded distributions are approximately evenly divided. However, when distributions of biological metrics are skewed in Reference or Degraded conditions, scoring without the accounting for the BSP will provide less meaningful scores. The percentage of Ephemeroptera individuals excluding individuals from the family Baetidae (EPHEMEROPTERA_NO_BAETID) exemplifies the potential issue with the CAU scoring methodology (Figure J-1). It is a sensitive metric for the family-level Inland index. In Figure J-1, the distribution of both Refence and Degraded samples extend from 0 – 100 but this metric was considered sensitive to the defined disturbance gradient (DE = 80.7%, BDE =78.4%) and the metric depicts a declining trend from Reference to Degraded. Applying the CAU scoring methodology, the ceiling would be set at a metric value of 52.5% and the floor would be 0%; therefore, a score of 50 would be equivalent to a raw metric value of 26.3%. Using the BSP to inform the continuous scoring gradient, a score of 50 would be equivalent to a raw metric value of 13.4%. The distribution of CAU-scored PCT_EPHEMEROPTERA_NO_BAETID would be similar to Figure J-1 and would continue to discriminate between Reference and Degraded distributions well. However, a CAU score of 50 is difficult to interpret because it represents the midpoint of the range of metric values and is more influenced by the proportions of good and bad sites than the defined disturbance gradient. A score of 50 from a scoring method incorporating the BSP better identifies metric values that are found in the middle of the disturbance gradient. As scores increase from 50, more confidence is gained that the sample represents a Reference condition. As scores decrease from 50, more confidence is gained that the sample represents a Degraded condition.

*Figure J-1. The box-and-whisker plots represent the distribution of raw metric values for the percentage of Ephemeroptera individuals excluding individuals from the family Baetidae (PCT_EPHEMEROPTERA_NO_BAETID) in each disturbance gradient category. The red dotted line at 13.4% represents the BSP for the metric and receives a score of 50. The gray dashed line at 26.3% represents the value that would be scored 50 using the CAU scoring methodology (floor = 0, ceiling = 95th percentile of all values). Numbers at the top are the sample size of each disturbance gradient category.*

### Results

The metrics selected for the family-level Inland index were used to examine the different outcomes of the the four scoring methods. Figure J-2 depicts the distribution of each scoring method relative to the disturbance gradient categories. The methods do not provide the exact same results but each method distribution roughly represents a truncated or elongated distribution of the other three methods. The Balanced Discrimination Efficiency method used to score metrics for the Chessie BIBI is best at spreading index scores from a broad range of environmental conditions across the entire 0 – 100 scale. Median scores in Reference and Degraded conditions also show the greatest separation. For CAU and Chessie BIBI, scores in Reference conditions fall mostly above 50, the mid-point of the 0 – 100 index scale, and scores in Degraded conditions fall mostly below 50. Classification efficiencies are essentially the same across all four methods.

_Figure J-2. Distributions of index scores for family-level Inland index scored using four scoring methods: All Gradient based on the minimum and maximum values from all of the available data (ALL GRAD), All Gradient based on the 5th and 95th percentiles of all of the available data (ALL GRAD (5, 95)), Reference Gradient (REF GRAD), and the scoring procedure outlined in this report (CHESSIE BIBI). The whisker lengths are designated by the Interquartile Range multiplied by 1.5._

The approach used in this report to assign narrative rating to index scores was applied to all four scoring method outcomes, i.e., rating thresholds are the 50th, 25th, 10th and half of 10th percentiles of the Reference distributions (II. M. Narrative Rating Categories). The proportion of sampling events in each of the five rating categories is summarized in Figure J-3. The proportion of sampling events classified as Excellent, Good, and Fair differed by less than 2%. The proportion of Excellent, Good, and Fair sites is the measure used by the Chesapeake Bay Program to track improvement in stream health. Proportional differences between the Poor and Very Poor rating categories were greater. The ALL GRAD and CAU methods had low proportion of Very Poor sampling events and the REF_GRAD and Chessie BIBI methods had the highest proportions.

The larger proportion of sampling events classified as Very Poor in the REF GRAD and CHESSIE BIBI is because the index scoring scale is determined by percentiles of the values in Reference conditions rather than in the entire data pool. The range of metric values used to create the 0 – 100 scoring scale for the ALL GRAD and CAU methods is larger and has a lower threshold for degraded biological condition than the range of metric values used to create the 0 – 100 scale for the REF GRAD and CHESSIE BIBI methods. Thus, metrics scored with the REF GRAD and CHESSIE BIBI methods tend to have a greater proportion of samples rated as Poor or Very Poor than the ALL GRAD and CAU methods.

_Figure J-2. Distributions of index scores for family-level Inland index scored using four scoring methods: All Gradient based on the minimum and maximum values from all of the available data (ALL GRAD), All Gradient based on the 5th and 95th percentiles of all of the available data (ALL GRAD (5, 95)), Reference Gradient (REF GRAD), and the scoring procedure outlined in this report (CHESSIE BIBI). The whisker lengths are designated by the Interquartile Range multiplied by 1.5._

_Figure J-3. A standard rating protocol was applied to each scoring method and the stacked bar plots represent the percent of samples in each rating category._

### Conclusion

CBP ultimately wants to increase the proportion of stream miles supporting health stream communities in the Chesapeake Bay watershed. All four of the scoring methods tested are roughly equal in their ability to classify Excellent, Good, and Fair health. Because the REF_GRAD and Chessie BIBI methods are derived from metric values observed in least-disturbed, or Reference, streams, they are better able to identify biological communities that diviate substantially from a healthy status. This is seen in their larger proportions of Very Poor status in Figure J-3.