---
title: "Conclusions and Recommendations"
output: html_notebook
---

##  Sample Collection

A major difficulty in refining the Chessie BIBI was the discrepancies in the habitat and water quality variables rather than differences in macroinvertebrate collection and identification methods. Environmental condition classification is a major aspect of IBI development. The water quality and habitat factors used to classify samples as Reference and Degraded influence which metrics are selected in the final index. For example, site classification based strictly on nutrient criteria and site classification based on habitat variables are likely to produce two different IBIs even though the same data were utilized. None of the habitat or water quality variables in our database were measured at all sampling events, and a subset of frequently measured variables was used in the development of the indices. Agencies/programs can argue that their protocols are tailored to address specific needs, so their data do not need to be compatible with other data. However, standardizing procedures makes it easier for programs to collaborate, review, verify previous conclusions, and rapidly improve the science. Collecting at a minimum the habitat parameters outlined in the visual-based Rapid Bioassessment protocol (Barbour et al. 1999), in a consistent fashion, and specific conductivity, pH, DO, and temperature—measurements easily collected with the average sonde—would be very beneficial. The collection of ancillary parameters, such as total nitrogen, would further improve our understanding of aquatic ecosystems but these parameters should be collected in addition to the standard parameters, not in place of the standard parameters. A standard set of procedures would also make it easier to perform cooperative assessments.

The CA, MAC, BLUE, and PIED bioregions lack adequate Reference and/or Degraded sample sizes for robust index development. Other bioregions, such as NAPU, showed unexpectedly low CEs. Targeting specific streams expected to be of Reference or Degraded quality within each of these bioregions would most likely improve index performance in future refinements. A review of land use and USGS gauges or other water monitoring data could help identify streams that meet these condition categories. Additionally, it may be beneficial to include data collected outside of the Chesapeake Bay watershed. Many of the bioregions or ecoregion level III’s within the basin extend beyond the limits of the basin. Including samples outside of the basin increase sample sizes and would especially benefit poorly represented bioregions. For example, the MAC bioregion represents the northern extent of Level III Ecoregion 63 (Woods et al. 1999). Expanding the MAC area to include portions of North Carolina and South Carolina represented by ecoregion 63 would increase sample size and may ultimately improve index performance. The samples outside of the basin would only be used during index development. Chesapeake Bay watershed assessments would remain limited to the samples located within the basin.

Spatial distribution of Reference and Degraded sample locations could be factored into a program’s sampling design to further reduce the potential of spatial bias. Although this effort would be conducted at the bioregion level, the performance of region indices would also improve, or at the very least, confidence in the current indices would improve. Furthermore, there are many HUC12s within the basin that are underrepresented (Appendix L). Collecting samples from these locations would benefit basin-wide assessments but should be considered a secondary goal behind the primary effort to target Reference and Degraded sites. 

## Data Analysis

Quantifying land use in the watershed above a sampling station may improve the classification of samples along the disturbance gradient. There are connections between stream biota and watershed land use through stream habitat and water quality conditions. The HUC12 land use variables in Appendix H provide an approximation of the watershed conditions above the sampling station. We recommend watersheds be delineated from the sampling station to aid in environmental condition classification. Delineating watersheds from the sampling location in ArcGIS will improve land use estimates in the catchments above sample locations, but the process will require extensive QA/QC. The most difficult aspect will be accurately placing the sampling station on the appropriate stream. Low accuracy in GPS equipment and inaccuracies associated with GIS stream layer location caused a significant portion of the stations in the Chessie BIBI database to fall outside the stream lines in ArcGIS. ArcGIS tools can be used to snap the points to the stream lines but many streams in a small geographic area may result in the sampling station snapping to the wrong stream. Therefore, effort would be required to validate that watersheds have been accurately delineated for all the sampling stations in the database.

An important issue that became apparent during the refinement of the Chessie BIBI was the absence of tolerance value, functional feeding group (FFG), and habit assignments for a subset of taxa. Tolerance, FFG, and Habit metrics are considered essential for diversifying and creating a robust IBI. Error is introduced when calculating metrics from these three categories if a taxon or taxa are not assigned the appropriate numerical or categorical variable. Assigning new tolerance values, FFGs, and habits requires extensive investigation and was beyond the scope of this study. Collaboration among multiple agencies/programs could be helpful in the assignment of future traits. Often taxa are not assigned traits because they occur infrequently but a large cohesive dataset may provide enough data for an accurate assignment of taxonomic attributes to these rare taxa. An effort was made to summarize taxonomic traits from multiple sources. We concluded that aggregating assignments from multiple categories provided the best representation of the taxa of interest. We recommend that efforts be continued to update the current set of attributes/traits and to include additional attributes/traits from additional sources.

The classification system used to identify Reference, Degraded, and intermediate site conditions (Table 2 and Table 3) forms a step-wise, or non-continuous, stressor axis based on commonly measured physical and chemical parameters. Distinctly different biological metric values, metric scores, and Chessie BIBI index scores are found at each step along the axis. This stressor-response relationship is reminiscent of the Biological Condition Gradient (BCG), a conceptual framework relating six tiers of biological responses to a gradient of increasing stress on aquatic ecosystems (USEPA 2016c). The BCG is intended to more precisely define and measure biological status, better recognize the quality of reference sites, document the effectiveness of restoration efforts, identify anthropogenic stressors, and help establish biocriteria in water quality standards. The BCG stressor axis represents the cumulative effects of all physical, chemical, and biological factors adversely affecting aquatic biota whereas this study’s stressor axis only reflects eight physical and three chemical factors. Rough approximations can still be drawn between the two. Biota in this report’s Reference conditions equate approximately to BCG Level 2, which has biological “structure and function similar to natural community with some additional taxa and biomass, and ecosystem level functions are fully maintained” (USEPA 2016c). Likewise, populations in Degraded conditions are roughly equivalent to BCG Level 5, where sensitive taxa are markedly diminished, distributions of the major taxonomic groups are conspicuously unbalanced, and ecosystem functions show reduced complexity and redundancy.

Results of this study could be used to quantify some of the biological attributes needed to construct regional BCGs. For example, attributes II (highly sensitive taxa), III (intermediate sensitive taxa), IV (intermediate tolerant taxa), and V (tolerant taxa). Study results could also support BCGs already developed for parts of the Chesapeake watershed (e.g., Stamp et al. 2014). 

## Assessments

To assess stream health in the Chesapeake Bay basin as a whole, the selected index should consider CE, precision, accuracy, and parsimony. Unnecessary complexity increases the potential of introducing error in future assessments. When multiple taxonomic and spatial versions of the index show roughly the same sensitivity, it is beneficial to select the simplest index or set of indices. For region and bioregion indices, CEs of the family-level versions were generally comparable to the genus-level version (Table K-2 and Table K-3), therefore, the family-level assessments were selected as the parsimonious taxonomic level. The Chesapeake-wide index was the most simplistic index developed but results suggested that underlying environmental factors, independent of stream condition, were confounding results. CEs of the region indices were generally comparable to the bioregion indices, and thus, the region indices were the most parsimonious spatial resolution. The family-level region indices are recommended for Chesapeake watershed-wide assessments. They standardize metrics and scoring thresholds over large areas of the basin, allowing for direct comparison of index scores among most sampling events. They can provide a robust indicator of stream health at either the region and bioregion scales.

We recommend using the region and bioregion indices in concert to assess local (e.g., restoration) sites in the Chesapeake watershed. Both spatial resolutions contain varying amounts of error. Scores and ratings provided by the regional indices can be directly compared across large portions of the basin; for example, scores in BLUE can be compared directly to scores in UNP. Scores and ratings from the bioregion indices may be more sensitive to localized nuances and more affected by differences in monitoring program methodology. Since the region and bioregion indices were developed separately, they can be treated as independent measures. Confidence in the results improves when both spatial resolutions are in agreement (Table 18). If both spatial resolutions of the index classify a sampling station as “Very Poor,” then the sampling station may be a prime candidate for restoration activities. If both spatial resolutions classify the station as “Excellent,” then the station may benefit from conservation actions. Disagreement between the ratings will require the sampling stations to be review on a case by case basis. In general, the most conservative action would be to assume that lower of the two ratings is the most accurate. The area will then need to be reviewed further before making a final determination. A more in-depth comparison of the two spatial resolutions may be beneficial but could be erroneous. For example, the region index may classify a station as “Poor” and the bioregion index may classify the station as “Good.” This result could be interpreted as the sample is considered to be “Poor” relative to the majority of the Chesapeake Bay watershed but relative to the samples within the bioregion the station tends to have a higher score. Therefore, this station may benefit from some restoration activity but relative to the other samples in the bioregion it should not be considered a top priority. This approach should be used with caution because the difference could be due to a weakness or error in the index and may not reflect differences in spatial resolution.

The Chesapeake Bay Program (CBP) is seeking a measure of stream health to monitor restoration progress within the Chesapeake basin. Because the sampling stations are not evenly distributed throughout the basin, we recommend that the samples be area-weighted. Area-weighting the index scores reduces the spatial bias associated with heavily sampled geographic areas, enabling an accurate summary of the basin to be derived. In the past, CBP has focused on the basin-wide percentage of streams categorized as Excellent, Good, or Fair. Using the area-weighting method, we estimate approximately 49.2% (region indices) and 49.2% (bioregion indices) of streams assessed in the Chesapeake basin were in Excellent, Good, or Fair condition over the 1992 – 2015 time period. Approximately 11.3% (region indices) and 13.6% (bioregion indices) have insufficient samples and could not be evaluated. An objective of the CBP is to develop a 2008 baseline against which CBP can measure progress in restoring stream health. This study provides the framework and the necessary data for the Stream Health Workgroup to construct the 2008 baseline.

The Chessie BIBI is an ever-evolving index. Admittedly, the biological data in the Chessie BIBI database are prone to bias due to differences in sampling technique, enumeration technique, and taxonomic resolution among agencies/programs. Several steps were taken to extensively groom the database and reduce the influence of any existing, known bias. We believe the benefits of combining multiple data sets outweighs the inherent biases. Sample size, and therefore, statistical power increases. The data set can transcend geopolitical borders, allowing for contiguous analysis within geographic areas deemed environmentally similar (i.e., regions and bioregions). Benthic macroinvertebrate assessments are often limited by time and funding. Many agencies/programs struggle to find an adequate sample size to develop or update an IBI in their region and they are constrained by political borders not observed by the fauna. We strongly recommend that IBIs be developed in cooperative manner between agencies/programs. Larger, cohesive data sets will improve statistical power, and the effort will be divided among multiple partners. Collaboration will also provide a succinct set of results that will be more readily interpretable by non-experts; as opposed to differing index values and ratings for the same general area reported by multiple agencies/programs (Maxted et al. 2000).

The Chesapeake Bay Program (CBP) is seeking a 2008 baseline of Chessie BIBI scores and ratings for monitoring restoration progress in the basin. Establishing the baseline requires attention and direction from CBP. The baseline will have to be derived from multiple years of data to overcome spatial and temporal gaps. Data collected between 2000-2011 are the most prospective candidates for establishing the baseline because most of the Chessie BIBI data currently in the database were collected during that time period. Stations that are periodically sampled provide the best data source for determining trends. Without a subset of repeatedly sampled stations, it is difficult—but not impossible—to determine if observed trends are a response to restoration efforts and not the result of temporal or spatial variability inherent in the random sampling design applied by many agencies/programs. The CBP objective to document trends in stream health would benefit from agencies/programs periodically returning to existing stations. To measure trends, we recommend long-term monitoring programs should collect benthic macroinvertebrate samples at a predefined frequency (e.g., every 5 years) from stations that represent the range of stream conditions.