---
title: "Discussion"
output: html_notebook
---

The objective of this study was to refine the existing Chessie BIBI, a stream benthic macroinvertebrate index of biotic integrity that evaluates stream biological communities with a common rating approach across the Chesapeake Bay watershed. The study is more rigorous than earlier attempts by Foreman et al (2008) and Buchanan et al. (2011), in part because of a recent update of the Chessie BIBI database. A version of the index was tailored to three spatial scales and three taxonomic levels using the stream macroinvertebrate metrics determined as most sensitive to disturbance at that scale and taxonomic level. Metric scores are average to obtain an overall index score for each spatial-taxonomic version of the index.

## Spatial Scales

A single index that applies to all streams and wadeable rivers in the Chesapeake Bay basin would allow for an uncomplicated assessment of stream health. Although superficially promising, the single index does not account for regional differences in the Chesapeake Bay watershed’s natural features or for the wide-spread landscape manipulation and degradation in the coastal region. Natural differences in hydrologic and topographic features of the coastal and inland regions correspond to strong natural differences in stream macroinvertebrate communities (Appendix G and H). The coastal region also has a paucity of high quality sites, a fact that is well recognized (e.g., Maxted et al. 2000). The few Reference sampling events in the coastal region were overshadowed by the more numerous Reference sampling events in the inland region, effectively turning coastal sites into outliers during index development of the Chesapeake-wide index. The Chesapeake-wide index does not fairly represent biological responses to stream degradation in the coastal region, and is not recommended.

Creating separate indices for the Coast and Inland regions produces more reliable assessments of stream biological condition in the Chesapeake watershed. The Coast region is defined by the Middle Atlantic Coastal Plain (MAC) and Southeastern Plain (SEP) Level III ecoregions and has mainly low elevation, low gradient, hydrologically connected streams with unconsolidated substrates (Woods et al. 1999). The Inland region is represented by a wide range of stream gradients, elevations, and substrates. It makes up a large portion of the Chesapeake Bay watershed, extending from southern Virginia to southern New York. All three taxonomic versions of the Inland region indices had CEs greater than or equal to 70.0% (Table K-2). The family- and genus-level Coast region indices were greater than or equal to 70.0% and the order-level CE fell just below this threshold (CE = 69.5%). Area-weighted ratings of the Coast and Inland region indices can be used together to represent stream biological integrity across the entire Chesapeake watershed (e.g., family-level Coast index and family-level Inland index). Sensitivity of the Coast index is currently impeded by a paucity of Reference sites in the MAC bioregion. The strong agreement between the family- and genus-level versions of the Inland index suggest they could be used interchangeably in Inland areas (Table 20B).

Further dividing the Chesapeake Bay basin into twelve bioregions provides more spatial resolution of the basin’s complex natural features and accommodates some natural differences in least-disturbed stream macroinvertebrate assemblages (Appendix G). The greater spatial resolution helps to avoid situations experienced in Buchanan et al. (2011) where high numbers of Reference and Degraded samples in one area dominated index development in an entire bioregion. A good example is the original 2011 Piedmont bioregion, where most of the Reference and Degraded samples available at the time were from what is now the Lower Northern Piedmont (LNP) bioregion (Buchanan et al. 2011). The LNP area contains the heavily sampled Washington D.C. suburbs, and development of the 2011 Piedmont index was dominated by that data. Similarly, indices for the 2011 Ridge and Valley bioregions were heavily weighted by Reference samples collected in their less disturbed, southern areas. The 2011 Ridge and Valley bioregions are both complex and large, bisecting the entire Chesapeake Bay basin on a northeast-southwest axis. In this study, these two bioregions were divided into six smaller, more homogeneous bioregions based on the Bray-Curtis Dissimilarity Index results of a stream classification analysis (Appendix G): Northern Ridge and Valley (NRV), Southern Ridge and Valley (SRV), Blue Ridge (BLUE), Central Appalachians (CA), the Southern Great Valley (SGV), and a portion of the Upper-Northern Piedmont (UNP). One bioregion that may benefit from subdivision in the future, when more data are available, is the Northern Appalachian Plateau and Uplands (NAPU). Reference sites in this bioregion are concentrated on the eastern side (Level IV Ecoregion 60b) and the bioregion’s family-level index has a low CE, which suggests divergent landscapes are reducing the index’s CE. 

## Taxonomic Versions

Bioregion and region indices derived from order-level metrics were developed in an attempt to create a coarse field method for rapidly screening stream condition. Functional feeding group (FFG), habit, and some tolerance metrics are inappropriate at the order-level, which leaves richness/diversity, composition, and a subset of tolerance metrics to be included in order-level versions of the indices. The Inland order-level index was considered sensitive to stream conditions (CE ≥ 70.0%) and the Coast order-level index CE was just below the sensitivity threshold (CE = 69.5%) (Table K-2). Nine of the twelve order-level bioregion indices had CE values greater than or equal to 70.0% (i.e., BLUE, CA, LNP, MAC, NRV, SEP, SGV, SRV, and UNP) but most had higher amounts of uncertainty as measured by RMSE relative to the Region order-level indices (Appendix K). Index development sometimes identified fewer than five metrics for inclusion in the order-level bioregion indices. For example, only four metrics met the criteria for inclusion in the order-level BLUE index (Table 13). This may reflect the low number of available degraded sampling events in BLUE. We recommend caution in using the order-level versions of both the region and bioregion indices. However, we believe with further work they can eventually be a resource for rapid in situ assessments and screening purposes—most likely conducted by non-experts. Volunteers and other non-experts can accurately identify benthic macroinvertebrates to the order-level with minimal training and equipment.

With few exceptions, the bioregion and region indices derived from family- and genus-level metrics had higher CEs than their order-level equivalents. Family- and genus-level taxonomic identification requires more extensive training and equipment to observe minute morphological features, such as gills, mouth parts, and leg segments. The genus-level versions did not increase CEs substantially over the family-level versions in most bioregions, and were lower in a few instances. The literature provides conflicting results on the benefits of identifying taxa to genus-level. Some studies have found that the genus-level provides additional information that allows for more accurate stream assessments (Lenat and Resh 2001, Pond et al. 2011) while other studies found that the genus-level provides minor improvements in the sensitivity compared to the family-level (Waite et al. 2004, Melo 2005, Corbi and Trivinho-Strixino 2006, Mueller et al. 2013). Genus-level identification produces a greater amount of information, allowing attributes to be more accurately assigned to the taxa and a better representation of assemblage richness and diversity. However, increased resolution may also increase the amount of noise associated with the assemblages. A larger number of rare taxa are likely to appear at the genus-level resolution and their presence may reduce the ability to identify robust sensitive metrics. Van Sickle et al. (2007) found that O/E models improved with the exclusion of rare taxa and they suggest that a similar improvement will likely be observed with other biological assessment methodologies. In this study, variability in metric selection introduced by probabilistic rarefaction is directly tied to the presence of rare taxa (Appendix D). Additionally, seasonal differences are more apparent at the genus-level than the family-level. Season was not accounted for in the Chessie BIBI in order to maintain sufficiently large Reference sample sizes. Pond et al. (2011) found that the West Virginia Genus-Level Index of Most Probable Stream Status (GLIMPSS) performed well when separate indices were developed for samples collected in the spring and summer. Separate seasonal indices may improve the performance of the genus-level Chessie BIBI indices in future analyses. 

## Distributions of Index Scores

Distributions of an individual metric’s values in Reference conditions are not identical across the twelve bioregions due in large part to the natural variation in the Chesapeake basin’s stream macroinvertebrate assemblages (e.g., Appendix G and I). The largest differences occur between the Coast and Inland regions. For example, percentages of EPT in Reference conditions are typically greater than 50% in the ten inland bioregions and less than 40% in the two coastal bioregions. Differences are also evident between bioregions located within the same region. For the bioregions located within the Inland region, percentages of burrowers decrease as watershed mean slopes become steeper. Although metrics are scored per their bioregion’s Reference and Degraded assemblages, bioregion differences carry through to the index scores. Consequently, the numeric score for one bioregion index is not necessarily equivalent to the same numeric score for another bioregion index (Pond et al. 2011).
Distributions of the bioregion index scores in Reference and Degraded conditions also are not the same across the twelve bioregions. This is true at the order-level (Figure 10 and 11), family-level (Figure 12 and 13), and genus-level (Figure 14 and 15), and occurs regardless of the methodology used to construct the index (Figure I-3). Likewise, for the two region indices, Coast and Inland, Reference and Degraded distributions of index scores are not identical (Figures 7, 8, and 9). Although the water quality and stream habitat criteria for Reference or Degraded conditions were applied consistently to all sites across the Chesapeake Bay watershed, other environmental factors influence stream biota (Appendix H) and can cause distributions of index scores in Reference conditions to shift. The standardized water quality and stream habitat criteria do not account for all the local factors influencing macroinvertebrate assemblages. Thus, the quality of Reference sites in one bioregion may in fact be higher or lower than that in another bioregion.

We recommend a certain amount of caution when using the BLUE, CA, and MAC bioregion indices. These bioregions had low numbers of either Reference or Degraded samples and consequently had high RMSE (Appendix K). Validation estimates indicate the family-level CA index overestimated CE (i.e., delete-d jackknife cross validation procedure). More samples are required in the BLUE, CA, and MAC bioregions to further refine these indices and verify their accuracy.

## Narrative Ratings

The 50th, 25th, 10th, and half of the 10th percentiles of the Reference distributions, excluding outliers, in each spatial and taxonomic version of the index were used in this study to establish five ratings: Excellent, Good, Fair, Poor, and Very Poor (Table 5). This common narrative rating system reduces the unevenness of the distributions of Reference index score and allows narrative ratings to be compared across bioregions and regions. An Excellent rating derived from the family-level index in one bioregion should be roughly equivalent to an Excellent rating derived from the family-level index in another bioregion because both ratings represent index scores greater than the 50th percentile of their respective Reference distributions.
Ratings for this study’s twelve-bioregion index and the Buchanan et al. (2011) six-bioregion index, which used some of the same percentiles to rate family-level index scores, were comparable with 84.6% (match = 47.2%, near = 37.4%) agreement in the Inland bioregions and 85.8% (match = 50.2%, near = 35.6%) agreement in the Coast bioregions (Table 18). It’s worth recalling that Buchanan et al. (2011) used somewhat different Reference criteria and metric scoring approaches for the inland bioregions, and employed the Coastal Plain Macroinvertebrate Index created by Maxted et al. (2000) for the coastal region.

The natural features collectively represented in bioregion do not appear to substantially change the narrative ratings of the two family-level region indices relative to the twelve family-level bioregion indices (Appendix M). Most bioregions showed less than ± 10% difference between their region and bioregion index ratings in the frequency of desirable Excellent, Good, and Fair ratings (%EGF). Rating differences are also less than ± 10% in most of bioregions when scores and ratings of the region indices are compared by season and karst. These results corroborate direct comparisons of individual ratings which show less than 10% disagreement between the bioregion and region family-level index ratings (Table 20A). Overall, the bioregion, season, and karst differences are not large enough to dissuade use of the family-level region indices.

Discrepancies in three bioregions raise the question of which spatial resolution—region or bioregion index—provides the most accurate depiction of stream condition. The CA bioregion, which is split into three non-contiguous areas inside the Chesapeake Bay watershed (Figure 3), has a limited number of sampling events that meet the Reference criteria (n = 35). The MAC bioregion inside the Chesapeake watershed has even fewer Reference sampling events (n = 17). The BLUE bioregion has adequate numbers of Reference samples for index development (n = 133) but only seven samples representing Degraded conditions. Until CA and MAC have more Reference samples and BLUE has more Degraded samples, the family-level Inland and Coast indices produce more realistic evaluations of stream health in these three bioregions. To develop more robust indices, the CA and MAC bioregions may benefit from the incorporation of samples outside of the Chesapeake Bay watershed but still within their respective bioregion/ecoregion.

In several bioregions, bioregion index scores and %EGFs in the Reference conditions differ substantially from their region index counterparts (Appendix M). Data preparation and standardization steps minimize or eliminate most field and laboratory variables that may cause conflicting ratings. A consistent, methodical approach was used to develop each version of the index, and the bioregions in question have sufficient numbers of Reference samples. The differences may be caused by less stringent or different methods used by some monitoring programs to evaluate stream habitat parameters (Appendix M) which result in higher habitat scores. These samples would technically meet the eight habitat parameter criteria for Reference (Table 3) and be included in the Reference pool. Reference distributions of the index scores determine the rating thresholds, and %EGF in Reference conditions will be dragged down if a significant portion of the Reference data pool is of a lower quality relative to other bioregions. At the regional scale, the influence of these samples is minimized by larger numbers of Reference samples collected by multiple programs. We believe the indices of at least NAPU, UNP and LNP—and possibly other bioregions—are affected by this issue.

When sites are being assessed individually with internally consistent methods (e.g., to measure restoration “lift”), the genus-level versions of bioregion indices may be useful if they are substantially more sensitive than their corresponding family-level versions (e.g., NRV in Table K-3). The inherent effect of seasonality on the genus-level metrics, however, may make the family-level indices more reliable to use when merging data from different monitoring programs. Good comparability in the ratings is found between the family-and genus-level versions of the Inland region and bioregion indices (Table 20B and C). Ratings of the family- and genus-level versions agree 90.3% in the Inland region index (Table 20B) and 91.4% in Inland bioregion indices (Table 20C). We view cautiously the apparent good agreement in ratings of the order- and family-level coastal bioregion index (Table 20C) given the poor agreement in other coastal index comparisons.

