---
title: "Executive Summary"
output: html_notebook
---

# Executive Summary

The “Chessie BIBI,” or Chesapeake Basin-wide Index of Biotic Integrity, is a multi-metric index that measures the biological quality of streams and wadeable rivers on a common scale. It is calculated from macroinvertebrate data collected by federal, state, and local stream monitoring programs in the Chesapeake Bay region. The index was first developed in 2011. This refinement was done for two reasons: recent additions to the stream macroinvertebrate database significantly increased the potential to hone the index’s sensitivity, and it is now possible to develop and test genus-level metrics.

The analysis database contained 25,067 sampling events from across the Chesapeake Bay watershed. Sampling sites in 1st to 4th order streams were classified into five disturbance categories based on habitat and water quality information: Reference (best quality), Minimally Degraded, Mixed (indeterminate quality), Moderately Degraded, and Degraded (poorest quality). Biological populations in Reference streams represent the best attainable community structure and function and were used as a benchmark to measure the biological integrity of other streams. Key attributes of the stream macroinvertebrates (taxonomic serial number, functional feeding group, habit, pollution tolerances) were reviewed and updated. Eighty-four metrics were calculated from the raw counts of March to November samples. Metrics were scored with a method that identifies Reference and Degraded sites equally well. Metrics selected for the index were typically the most sensitive to degradation. Eight possible constructs for a multi-metric index were examined.

To address different information needs, the Chessie BIBI index was developed for two spatial scales: bioregion and region. The twelve bioregions accommodate natural variation in stream biota caused by hydrology, topography, and climate. The bioregion-specific indices are particularly suited for identifying local reasons of changing stream conditions and for measuring biological responses to restoration efforts. A coarser spatial division into the Inland and Coast regions proved most effective for reporting stream health for the Chesapeake Bay watershed as a whole. The Inland and Coast indices are sensitive to degradation but do not necessarily reflect natural differences between the bioregions.

Metrics keyed to order-, family-, or genus-level attributes were used to build versions of the index for different taxonomic resolutions of the raw counts. Order-level metrics are less sensitive, but they do not require laboratory enumeration and are suited for rapid screening in the field. Family-level metrics performed very well in most cases. They are recommended for use in the bioregion and region indices. Genus-level indices performed marginally better than family-level indices in some but not all bioregions. This is likely because genus-level metrics are affected by seasonal differences that are not accounted for in the indices.

A common scale of five narrative ratings was applied to the index scores of each taxonomic and spatial version of the Chessie BIBI index to compare stream health across jurisdictional boundaries in the Chesapeake watershed. The 50th, 25th, and 10th percentiles of each version’s index scores in Reference environmental conditions were used to define Excellent, Good, Fair, and Poor macroinvertebrate status. A fifth rating, Very Poor, was defined by half the value of the 10th percentile. Paired comparisons demonstrate the family-level versions of the bioregion and regional indices produce comparable ratings in all but the Mid-Atlantic Coastal (MAC) bioregion.

The family-level region (Coast, Inland) indices are recommended for assessments of the Chesapeake Bay watershed. The region indices represent large geographic areas in the watershed. They have high CEs, and less complexity, lower metric variability, and lower variability in rating thresholds compared to the bioregion indices.

A simple count of the narrative ratings indicates biological integrity is Very Poor or Poor at 49.5% of sampling sites and Fair, Good, or Excellent at 50.5% of sites in the entire, updated database (1992 – 2015). The counts are roughly comparable to those reported in 2011 for the 2000-2008 period (Very Poor or Poor at 54% of sites and Fair, Good, or Excellent at 46% of sites). Straightforward counts such as these are misleading, however, because some areas—especially urban ones around Washington, D.C.—are more heavily sampled than others. When station ratings are weighted by the proportion of their local (HUC12) watershed area they represent and the weighted ratings are summed, the results indicate stream health is likely Very Poor or Poor in 39.5% of the Chesapeake watershed; Fair, Good, or Excellent in 49.2% of the watershed; and not known in 11.3% of the watershed. Many unsampled HUC12 watersheds are in predominantly agricultural or forested areas and, when sampled, may improve percentages of the Fair, Good and Excellent ratings. Area-weighted ratings provide a better starting point for measuring trends than simple counts of the ratings.

Like all indices, the Chessie BIBI index is dependent upon the idiosyncrasies of the data used to build it. The benefit of a large database is the increase in statistical power and the ability to transcend geopolitical borders. We strongly recommend that IBIs be developed cooperatively, across jurisdictional boundaries, to allow for coordinated analysis and evaluation of regions that are environmentally similar (i.e., bioregions). Collaboration will enhance the accuracy and reliability of the macroinvertebrate attribute assignments used to calculate many of the metrics. It will provide a succinct set of results that are more readily interpreted by non-experts—as opposed to differing index values and ratings reported by multiple programs for the same region.

Refinement of the Chessie BIBI was hampered by the fact that only eight habitat and three water quality parameters occur frequently enough in the database to be useful in classifying stream environmental conditions. There was also uncertainty in how various monitoring programs score the habitat metrics described in EPA’s Visual-Based Rapid Bioassessment protocols (Barbour et al. 1999). We recommend stronger efforts to ensure that a standard suite of habitat and water quality measurements are made with comparable methods at all stream biological monitoring sites across the Chesapeake watershed. These measurements will benefit stream biological assessments in the long run. They will also improve each jurisdiction’s ability to track and report incremental improvements in stream functions (“lift”) that have not yet reached the point of benefiting biological populations and stream ecological health.
Facing page: Chessie BIBI (family-level version of the Region Index) ratings for streams and small rivers in the Chesapeake Bay watershed. When sufficient data (n > 3 catchments) are available, HUC12 watersheds are colored per the rating of their average index score. Otherwise, individual sampling locations are indicated and colored per their ratings.