---
title: "Introduction"
output: html_notebook
---

# Introduction

Water quality assessments are often limited by geopolitical borders in the United States even though streams and rivers frequently cross state borders. Protocols performed by multiple independent monitoring programs can lead to inconsistent, fragmented assessments of waterbodies if those protocols are substantially different. In March 2008, Chesapeake Bay Program (CBP) partners combined state agency stream assessments in a map of stream macroinvertebrate impairment (Wolf 2008) and concluded the result could not adequately represent stream condition on a Chesapeake basin-wide scale.

The United States Environmental Protection Agency (USEPA) and Geological Survey (USGS) have used macroinvertebrates to evaluate United States waterbodies on a national scale. The USEPA collected 63 stream macroinvertebrate samples from across the 165,760 km2 Chesapeake Bay watershed as part of its 2004-2005 Wadeable Stream Assessment (WSA) (USEPA 2006). WSA was replaced in 2008-2009 by the National Rivers and Streams Assessment (NRSA) and that program collected 37 samples within the watershed (USEPA 2016a). The USGS National Water Quality Assessment (NAWQA) program collected 254 stream macroinvertebrate samples in the Chesapeake Bay watershed between 1993 and 2012, primarily from its Potomac and lower Susquehanna study units. These federal programs benefit from a standard protocol and strict QA/QC measures; the results provide a statistical estimate of stream status for large regions of the country. However, these data sets have limited use when evaluating stream status on smaller scales.

All the states and several counties in the Chesapeake watershed routinely monitor stream biota for regulatory purposes. Other groups monitor for research or to measure restoration. These programs collected and enumerated more than 25,000 stream macroinvertebrate samples between 1992 and 2015. Although field methods can differ, there is frequently more similarity between methods than dissimilarity. Creating a unified database of the raw data from the various data sets and evaluating them with a standard protocol vastly improves the statistical power to characterize stream status, identify stressors, and detect responses to restoration efforts. Stream macroinvertebrate samples collected using slightly different sampling and processing protocols require more intensive post-collection QA/QC measures. However, they can yield similar biological assessment results (Ostermiller and Hawkins 2004, Astin 2006, Friberg et al. 2006, Gerth and Herlihy 2006, Herbst and Silldorff 2006, Southerland et al. 2006, Astin 2007, Rehn et al. 2007).

In 2011, the Chesapeake Bay Program (CBP) developed a Basin-wide Index of Biotic Integrity for stream macroinvertebrates, known as the “Chessie BIBI,” for non-tidal streams and wadeable rivers in the Chesapeake Bay basin (Buchanan et al. 2011). The Chessie BIBI stems from the work of Astin (2006, 2007), who integrated existing data collected by seven agencies/programs and developed a wadeable stream index for the Potomac River basin.

Foreman et al. (2008) and Buchanan et al. (2011) subsequently expanded the index to the entire Chesapeake Bay basin, an area of approximately 165,760 km2 that extends across seven states/districts (i.e., VA, WV, MD, DC, DE, PA, and NY) and several geomorphic regions. The index quantifies stream health seamlessly across jurisdictional boundaries in the Chesapeake Bay watershed. It is the stream health indicator named in the Strategy for Protecting and Restoring the Chesapeake Bay watershed (Executive Order 13508, 2010) and is identified in the Management Strategy for the Stream Health Outcome (Chesapeake Bay Program 2015) as the indicator for tracking improvements in stream health and function above an as yet undetermined 2008 baseline.

A refinement of the 2011 Chessie BIBI index was performed at this time for two reasons: recent additions to the stream macroinvertebrate database significantly enhanced the potential to hone the index’s sensitivity, and it is now possible to develop and test genus-level metrics. The project evaluated: (1) intra-agency/program data integration, (2) multiple spatial scales, (3) site classification parameters, (4) new and old biological metrics, (5) metric scoring methodologies, (6) eight constructs of a multi-metric index, (7) the applicability of order, family, and genus level biotic indices, and (8) area-weighting of the index ratings to remove spatial biases. R-scripts were written to make the procedure for calculating the index faster, repeatable, and more accessible to future analysts. A Technical Advisory Group (TAG) was established to aid the project and review products. Results of the Chessie BIBI refinement are intended to support the establishment of a 2008 baseline for CBP reporting purposes.