---
title: "R Notebook"
output: html_notebook
---

## Taxonomic Classification and Hierarchy

The taxonomic status of the benthic macroinvertebrate taxa identified in the Chessie BIBI database were confirmed with the Integrated Taxonomic Information System (ITIS) database (Retrieved [06/01/2016], from the Integrated Taxonomic Information System On-Line Database, http://www.itis.gov). Up to ten taxonomic ranks were assigned to each taxon when available and applicable: phylum, subphylum, class, subclass, order, suborder, family, subfamily, tribe, and genus (Appendix A). ITIS also provides a Taxonomic Serial Number (TSN), a unique positive integer assigned to each taxon. Taxa in the Chessie BIBI database were paired with the appropriate TSN. Taxa that were not found in the ITIS database but deemed valid based on a literature review were assigned a unique negative integer. A negative TSN will never overlap with the officially assigned TSN from ITIS, which will allow for the database to be continually updated without incorrectly assigning the same TSN more than once. When applicable, spelling errors were corrected and invalid taxonomic identifications were updated to reflect current taxonomic nomenclature. The reported taxonomic name is archived as originally stated but the updated taxonomic name was used during analyses. If the taxon was identified to a taxonomic rank not included in the database (e.g., Superfamily or Subgenus), the final ID was rolled up to the nearest taxonomic rank. Additionally, complexes (i.e., an unofficial grouping of two or more closely related taxa) were also rolled up to the nearest taxonomic rank included in the database. Complexes were excluded because they have the potential to incorrectly inflate richness and diversity values. The list of taxa was further reviewed by members of the Technical Advisory Group (TAG).

### Taxonomic Attributes
Calculations of many benthic macroinvertebrate metrics rely on assigned taxonomic attributes, or traits. Tolerance values, functional feeding groups (FFG), and habits were assigned from available sources (Barbour et al. 1999, USEPA 2008, Chalfant 2009, Bollman et al. 2010, Buchanan et al. 2011, USEPA 2012, WVDEP 2015, Smith 2016). Inconsistencies and gaps occur in the assignment of these attributes. In some cases, taxa have not been assigned a taxonomic attribute and assigning new attributes is beyond the scope of this study. In other cases, the sources that provided the attributes had differing assignments for the same taxon. If multiple sources provided tolerance values for the same taxon, the average of the tolerance values, rounded to the nearest integer, was assigned to the taxon. Categorical attributes (i.e., FFGs and habits) required more attention. Each categorical variable was assessed individually. For each attribute source and taxon, a total count of each variable was recorded. The variable with the highest total count was assigned as the final attribute. Another issue with categorical variables was that multiple attributes were often assigned to the same taxon within and between sources. Therefore, multiple taxa were assigned more than one attribute (e.g., collector-gather/predator) because all the variables had the same total count. Some of our attribute sources (USEPA 2008, Bollman et al. 2010, WVDEP 2015) assign multiple attributes to a single taxon to encompass attributes that are present at different life stages or the taxon exhibits a variety of attributes. Taxa with multiple attributes are effectively double counted in analyses; thus, incorrectly inflating the percentage of each metric class and resulting in a total percentage greater than 100% within a metric class (e.g., the sum of all percent FFG metrics). When the taxon with multiple attributes is abundant in the sample it has a substantial influence on two or more metrics within a metric category. To avoid any possible issues associated with multiple attribute assignments, each taxon with more than one attribute was reviewed and best professional judgement was used to select a single attribute to represent the taxon. The final attribute table was reviewed further by members of the Technical Advisory Group (TAG), and is provided in Appendix B. It should be repeatedly reviewed and updated in the future as individual taxa are better understood and characterized.

### Method Standardization

Differences in field and laboratory methodology can influence the taxonomic composition of samples and unintentionally bias analysis results. An analysis data set was created from the larger Chessie BIBI database that minimizes or removes the influences of many of these factors. Obvious factors were field method, stream size, and season. Only samples collected with a kick-net or a similar procedure were included in the analysis data set (i.e., D-Frame Net, Rectangular Dip Net, Kick Net, Kick Seine, and Slack Sampler). Hester Dendy Multi-Plate samplers, Surber Sampler, Hand-Picked samples, and unspecified collection methods were excluded from the analyses. Additionally, we limited our analyses to a Strahler stream order less than or equal to 4, which we considered to represent wadeable streams/rivers. Very few samples were collected between December and February (Figure 1). Samples collected during these months were excluded during analyses.

_Figure 1. All the kick-net samples in the Chessie BIBI database were aggregated together and the frequency of unique sample events were plotted for each month._

Undocumented differences in the laboratory procedures for enumerating stream macroinvertebrates can create bias. For example, some laboratories fail to explain their taxonomic identification rules beyond “the taxa were identified to the genus level or the lowest possible taxonomic resolution.” To reduce variability among agencies/programs, taxa were standardized to Operational Taxonomic Units (OTUs) (USEPA 2016a) deemed appropriate for the Chessie BIBI database (Appendix C). The data were reviewed for taxonomic inconsistencies and taxonomic standards were set to reduce inter-agency/program variability. Taxonomic information is lost when specifying OTUs but this loss was necessary to assess data acquired from multiple sources. To identify taxa inconsistencies in the database, the taxa were aggregated by agency/program and a total count was provided for each phylum, subphylum, and class.

Often it was apparent that some agencies or programs identified a taxon while others excluded the taxon from their assessment. For example, MD_MBSS and NYSDEC did not included mites (Chelicerata) during subsampling procedures, while other large data contributors, such as VADEQ, did include mites. As an additional confirmation, the number of sampling events containing the taxon and the mean relative abundance of the taxon in the samples for which the taxon was present were calculated. If it appeared that 1) at least one agency/program did not include a taxon, 2) the number of samples that the taxon was observed in was low (i.e., Phylum ≤ 5%, Subphylum ≤ 5%, and Class ≤ 1%), and 3) the mean relative abundance of the taxon was low (i.e., Phylum ≤ 3%, Subphylum ≤ 3%, and Class ≤ 1%), then the taxon was excluded entirely from the analysis. Although there is a loss of information and a minor loss in sample integrity, eliminating the taxon was a necessary action to reduce variability between agencies/programs.
We required counts of more than 70 individuals per sample in order to avoid skewing the percentage metrics in our analysis data set. If only two individuals were observed in a sample, each would receive a metric weight of 50% whereas when 100 individuals are observed each receives a metric weight of only 1%. Seventy was considered the greatest acceptable deviation from our lowest agency/program standard count (n = 100).

For the analysis data set, any taxon not classified within the phyla Annelida, Arthropoda, Mollusca, or Platyhelminthes was excluded. At the subphylum-level, taxa were excluded if they were not classified as Clitellata, Crustacea, Hexapoda, or Rhabditophora; if no subphylum-level existed within the ITIS database but the taxon could be classified within the four specified phyla, the taxon was not excluded from the analysis. At the class-level, taxa that were classified as Branchiopoda, Maxillopoda, and Ostracoda were excluded. Additionally, taxa within the families Gerridae, Hebridae, Velliidae, Hydrometridae, and Salidae were excluded from the analysis because they are classified as skimmer taxa. Skimmer taxa are considered semi-aquatic because they live on the surface of the water. They are not directly associated with the benthic macroinvertebrate communities, and therefore, should not be included in the development of a benthic macroinvertebrate index of biotic integrity. Finally, taxa of the order Hymenoptera were excluded because aquatic Hymenoptera are often small, parasitic organisms that may easily go unnoticed during processing. Carter and Resh’s (2013) review of state agency benthic macroinvertebrate indices indicated that a similar list of taxa are excluded by one or more agencies in the United States.
Figure 1. All the kick-net samples in the Chessie BIBI database were aggregated together and the frequency of unique sample events were plotted for each month.

Once the agencies/programs were standardized to exclude the same taxa, the taxonomic resolution of the organisms was assessed by agency/program. Generally, the lowest common denominator among agencies/programs was used to standardize the taxa. To observe different taxonomic resolutions, the taxa were first aggregated at a higher level taxonomic rank (e.g., Class). The total count at the higher level rank and subsequent lower level ranks were compared. If there was a large decline in the number of taxa identified at a higher level rank relative to the lower level rank, all taxa were rolled-up to the higher level rank during analysis. Bivalvia, Gastopoda, Oligochaeta, and Trepaxonemata taxa were rolled-up to the class-level, despite some agencies/programs identifying these organisms to the species-level. A relatively large number of Gastropoda individuals (n = 2,396) were not identified beyond the class-level. A conservative decision was made to aggregate all Gastropoda to the class-level. However, the 2,396 individuals not identified at the order-level only represented a 4% reduction from the individuals identified at the class-level. In future endeavors, it may be advantageous to aggregate Gastropoda at the order- or family-level, which may further improve index sensitivity to the defined disturbance gradient. Additionally, Collembola, Lepidoptera, Neuroptera, and Neoophora taxa were all rolled-up to the order-level. Again, this standardization process results in a loss of information but reduces the variability observed between the samples reported by each agency/program. It was difficult to assess the influence of agency/program beyond this point because sampling period, drainage, and ecoregion could confound observed differences. We concluded that the standardization process reduced the influence of agency/program on benthic macroinvertebrate composition, and subsequent divisions based on environmental factors addressed any remaining discrepancies.

### Rarefaction

Most agencies/programs have a standard subsampling procedure for randomly “picking” organisms from their stream samples. Standard counts are as low as 100 and some are greater than 500. Richness and diversity metrics are positively correlated with standard count because of the increased probability of finding rare taxa as the standard count increases (Gotelli and Colwell 2011). Such a relationship was observed in the Chessie BIBI database for family-level richness plotted against sample count (Figure 2).

_Figure 2. Sample with counts less than or equal to 600 (n = 22,240) were plotted against family richness. A base 10 logarithmic curve was generated with the available data._

To reduce the bias associated with sample count, all richness and diversity measures were calculated with each of the assemblages rarefied to a count of 100. A standard count of 100 was selected because it was the lowest common denominator among all the agencies and programs represented in the Chessie BIBI database. Rarefaction refers to a sample of the original assemblage without replacement until a standard count is reached. A hypergeometric distribution is formed when sampling without replacement (Bunge and Fitzpatrick 1993). We propose that the rarefied count of each taxon can be estimated, just as a rarefied richness can be estimated. We developed a modified rarefaction method, probabilistic rarefaction with R-programming (R Core Team 2016) using a combination of the rarefied richness and the rarefied counts (Appendix D). Probabilistic rarefaction reduces the variability associated with estimating taxonomic composition at a lower standard count, whereas, rarefaction is more susceptible to higher variability. We used probabilistic rarefaction for calculations of richness and diversity measures in this study.

### Biological metrics

Eighty-four biological metrics were identified in the literature (GADNR 2007, Pond et al. 2011, Carter and Resh 2013, Smith 2016). Additionally, the percentage of individuals in each Phylum, Subphylum, Class, Subclass, Order, Suborder, Family, Tribe, and Genus were systematically calculated when applicable. These additional composition metrics typically allowed for the assessment of 100-200 metrics.

During metric calculations, the taxonomic data were aggregated at a specific taxonomic level (i.e., Order, Family, or Genus). For Composition, Tolerance, Functional Feeding Group (FFG), and Habit metrics, the specified taxonomic level or the next lowest taxonomic level was used. However, richness/diversity metrics were only calculated using taxa identified to the specified taxonomic level. To prevent richness or diversity inflation, any taxon identified to a coarser taxonomic level was aggregated into an “unidentified” group.

The Hilsenhoff Biotic Index (HBI) and Modified Average Score Per Taxon (ASPT_MOD) calculations required each taxon in a sample to have an assigned TV. If the taxon did not have an assigned TV, it was not included in the calculation of these metrics. An issue arises when including taxa without TVs because these taxa are effectively assigned a TV of zero during metric calculations and would not accurately represent the sample. Therefore, the total number of individuals with an assigned TV was used as the denominator during TV related percentage metrics; taxa without TV were excluded from the calculations.

The metrics were calculated with custom R-functions (R Core Team 2016) and R-functions from the Vegan package (Oksanen et al. 2016). A complete list of the biological metrics, and their codes and descriptions, is given in Appendix E.