---
title: "Environmental Condition Classification"
output: html_notebook
---

## Environmental Condition Classification

Karr’s (1981) original fish IBI did not include the use of reference sites. After the introduction of the IBI concept, it quickly became apparent that assemblages collected at undisturbed sites could be used as a baseline to rate subsequent samples (Fausch et al. 1984, Karr 1991, Gibson et al. 1996). Reference sites typically represent the best obtainable or least-disturbed condition. Metrics indicative of degradation are discovered by performing pairwise comparisons of reference and test/degraded site metric distributions. Test sites represent all sites that were not considered reference, while degraded sites represent poor environmental conditions.

For this study, the condition of a sampling site was classified based on the three water quality parameters and scores of the eight habitat parameters above. Each water quality parameter received a score of 0 – 3 based on values used for state water quality assessments in EPA Region 3 or reported in the literature (e.g., Pond et al. 2011) (Table 2). Zero was assigned to the range of water quality values considered to be naturally occurring and to have minimal influence on stream macroinvertebrate survival. Reference thresholds for conductivity were selected after discussions with Technical Advisory Committee members and a review of the draft field-based methods for developing aquatic life use criteria for conductivity (USEPA 2016b). Reference thresholds for pH and dissolved oxygen were based on stream water quality standards in the Chesapeake basin states. Higher scores represented water quality conditions considered to be associated with anthropogenic stress and increasingly limiting to macroinvertebrate survival. Sites were classified as Reference if 75% or more of the available habitat scores were ≥ 16 and none were less than 12, and the sum of the three water quality scores was zero. Degraded sites had half or more of all available habitat scores ≤ 6 and the sum of the three water quality scores > 1. The Reference and Degraded environmental condition classifications (Table 3) were the only classes used to test metric sensitivity and index classification efficiency during the development of the indices. Three intermediate classes were also defined, i.e., Minimally Degraded, Mixed (includes all sites with insufficient data to classify condition), and Moderately Degraded. The Minimally Degraded and Moderately Degraded classes were used as a visual validation that the index was appropriately detecting ecological response on a declining gradient from the Reference to the Degraded environmental condition.

Sampling events were excluded if the number of individuals counted was less than or equal to seventy were evaluated for the rating system. Low sample counts may be indicative of a degraded condition, and thus, it may be appropriate to categorize these samples as “Very Poor.” However, when the low counts were associated with sample environmental condition classes there was no definitive pattern (Table 4). Although there were more Moderately Degraded and Degraded samples with low counts than Reference and Minor Degradation, most samples were classified as Mixed.

_Table 2. Criteria used to assign water quality degradation scores to each sampling event. A total sum of degradation scores equal to zero was necessary to meet Reference conditions. Sampling events with summed degradation scores greater than zero were classified as various levels of Degraded._

_Table 3. Site condition classifications. If more than five habitat scores were missing, the site could not be appropriately classified and were placed in the Mixed class._

_Table 4. The number of sampling events with less than or equal to seventy individuals identified, aggregated by environmental condition class._