---
title: "R Notebook"
output: html_notebook
---

## Area-Weighting of Rating Results

Several data processing steps were done to prepare area-weighted estimates of the percentages represented by each rating. All the data were used to map and compare ratings in this report, but most of the 21,552 samples in the final analysis database were collected in the 12-year period between 2000 and 2011 (Figure 6). This period dominates the results. The index scores of stations with multiple samples were averaged and the average rated to avoid giving any location disproportionate importance. The 21,552 sampling events in the analysis database condensed to 12,922 stations represented by a single sampling event and 2,154 stations represented by multiple (2-35) sampling events for a total of 15,146 stations. A check of unique locations identified by their latitude and longitude found 184 locations that shared 2 - 5 stations with different names. These cases are difficult to detect so we let them stand as unique stations.

_Figure 6. Sample count by year in the analysis database after the data preparation steps described in Methods were applied._

Randomly or systematically located stations are best suited for estimating the percentages of streams that can be statistically expected in each of the five rating categories. Monitoring programs usually indicate in their data sets or documentation how they selected their monitoring locations, and we incorporated this information into the stream database. In the analysis database, 3,689 (24.4%) of the 15,146 stations are currently listed as targeted and not random or systematic. This seems high given the number of monitoring programs that use random-stratified sampling designs or revisit stations that were first selected randomly. We believe there are inaccuracies in how some stations are classified in our database, and the true number of targeted stations is lower. For example, 2,981 (80.8%) of the 3,689 stations have only one sample and come from monitoring programs that typically do not target sampling locations. Thirty more stations are first listed as targeted and in subsequent years listed as random/systematic. These inconsistencies suggest that only 678 (4.5%) of the stations in the analysis database may be targeted sites. We decided to include all stations in the analysis database at this time, pending further investigation.

_Figure 6. Sample count by year in the analysis database after the data preparation steps described in Methods were applied._

Furthermore, combining data from multiple random sampling designs is not equivalent to a single, basin-wide random sampling design. Using a basin-wide random sampling design, each sampling location would have an equal probability of being selected. The random sampling design applied by each agency in the Chessie BIBI database were limited by the agencies study area (e.g., PADEP was limited to PA) and the number of samples collected by the agency. Different areas in the Chesapeake Bay watershed have different random sample densities, and therefore, each sampling location did not have an equal probability of being selected. To avoid giving heavily sampled areas an unfair weight, the rating for each station’s index score or average score was area-weighted. We used HUC12s as the basis for area-weighting because they are relatively small (10.7 – 197.1 km2) and homogeneous (67.8% fall entirely within the same bioregion). When a HUC12 overlapped two or more bioregions, the areas of each bioregion within the HUC12 were used to area-weight their respective scores (Table H-3). Sampling stations were aggregated first by high resolution catchments (“Retrieved [03/15/2017], from the ecosheds product downloads, http://ecosheds.org/assets/nhdhrd/v2/” n.d.). This reduced the potential for spatial autocorrelation caused by stations located close together with different names. The mean value of all station scores within each catchment was calculated and assigned a rating. Each catchment rating was then multiplied by the appropriate factor for its HUC12-bioregion unit:

_Equation 9._

All the weighted ratings for each rating category (Excellent, Good, Fair, Poor, and Very Poor) in a bioregion are summed and the sum divided by bioregion total area to obtain %Excellent, %Good, etc. 

For Coast and Inland, the two regional indices, station ratings are similarly weighted by how much of their respective HUC12-region unit they represent. Most HUC12s (1,922) fall entirely within one region; only 59 overlap the Coast-Inland boundary. The weighted ratings for each rating category are summed and the sum divided by the region’s total area to estimate the percent of streams in that category in the region. The weighted ratings can be rolled up to basin.