---
title: "Spatial Classification"
output: html_notebook
---

## Spatial Classification

Classifying least-disturbed streams into spatial units with similar features reduces the underlying “noise” in the data analysis and can reveal key relationships between biota and natural factors. Geology, topography, soils, vegetation, slope, and other natural factors affect the structure and function of stream macroinvertebrate assemblages (Kennen 1999, Feminella 2000, Hawkins et al. 2000). For example, taxa in stream assemblages on steep hillsides, with frequent riffles and falls, tend to be more adapted to high flow velocities than those in the flatter valleys or coastal plains. Taxa in karst regions can be more heavily influenced by cooler groundwater. Macroinvertebrates are more likely to disperse along connected stream corridors than across the mountain ridges or other barriers separating major drainage basins (Bilton et al. 2001, Petersen et al. 2004).

The natural landscape of the Chesapeake Bay drainage basin has been classified by hydrologic unit, physiography, and ecoregion. The hydrologic classification system was created by the United States Geological Survey (Seaber et al. 1987). It catalogs surface waters in a hierarchical system, dividing large hydrologic regions into successively smaller units. Hydrologic Unit Codes, or HUCs, indicate the level of classification. Geology and distinct landforms on the earth’s surface are the basis for physiographic classifications (Fenneman 1917). The Appalachian Highlands is the largest physiographic region along the east coast of North America, stretching 2,400 km (1,500 mi) from Newfoundland to central Alabama. Four provinces of the Appalachian Highlands contain most of the Chesapeake drainage area: Appalachian Plateau, Valley and Ridge, Blue Ridge, and Piedmont. The other major physiographic region in the Chesapeake drainage is the Atlantic Plain, which lies between the Piedmont province and Atlantic Ocean. Ecoregion, the third classification system, builds on physiographic provinces and considers non-geological factors such as climate, soils, elevation, and vegetation (Omernik 1987, Woods et al. 1999). Ecoregions subdivide physiographic provinces into relatively homogeneous landscapes that support distinct ecosystems.

Indices for three spatial scales were explored: 1) Chesapeake-wide, 2) region, and 3) bioregion. The Chesapeake-wide index used a single suite of macroinvertebrate metrics for the entire basin. The metrics generalize the response of benthic macroinvertebrates to one degradation gradient for the entire basin. The Chesapeake Bay basin is 167,000 km2, and this spatial resolution may be considered too coarse for index development. However, the National Rivers and Streams Assessment (NRSA) developed indices for geographic areas much larger than the Chesapeake Bay basin, such as the Southern Appalachians, Atlantic Coastal Plains, and Temperate Plains (USEPA 2016a). The feasibility of a single, basin index was explored for reporting purposes.

For the regional spatial scale, the basin was divided into two regions—Coast and Inland. Level III ecoregions 63 (Mid-Atlantic Coast) and 65 (Southeastern Plains) (Woods et al. 1999) were used to define the Coast region of the basin. The remaining ecoregions located in the Piedmont and Appalachian Highland provinces were aggregated to represent the Inland region. Hydrogeomorphologic differences between these two regions are well known in the literature (Maxted et al. 2000, Klemm et al. 2003, USEPA 2016a). Benthic macroinvertebrate assemblages in these regions are significantly dissimilar (Dail et al. 2013).

For the third spatial scale, the basin was divided into twelve bioregions. These were areas with distinct differences in their natural, undisturbed stream macroinvertebrate assemblages. Bioregion classifications identified in Buchanan et al. (2011) were confirmed or adjusted. Table 5 lists the bioregions in the Chesapeake Bay drainage that were identified; Figure 3 shows their locations. The bioregion scale was the highest spatial resolution used in this report. Indices developed for individual bioregions provide assessments for relatively small geographic areas and identify biological responses specific to disturbances in that area. Appendix G presents in detail how hydrologic unit, physiography, and ecoregion classification approaches were applied to arrive at twelve bioregions.

While bioregion classifications are intended to reflect differences in natural features, they also capture differences in anthropogenic features that can influence stream macroinvertebrate assemblages. We recognized that Reference conditions in one bioregion can differ from Reference conditions in another bioregion despite both bioregions meeting the eight habitat and three water quality criteria. The anthropogenic influences are not necessarily evident in the five environmental condition categories (above). They may include factors such as road density, upstream impervious cover, agricultural contamination of the hydrologically connected zone, groundwater withdrawals for agricultural irrigation that affect baseflow, and nitrogen deposition. The levels of some important natural and anthropogenic features in HUC12 watersheds are shown by bioregion in Appendix H.

_Table 5. Hydrologic and physiographic features used to delineate the twelve bioregions of the Chesapeake Bay basin._

_Figure 3. The Chesapeake Bay basin was divided into twelve bioregions for the Chessie BIBI refinement._