---
title: "R Notebook"
output: html_notebook
---

Of the 25,067 sampling events included in the stream macroinvertebrate database, 21,314 remained after applying the data preparation steps. The majority of sampling events in all bioregions represent intermediate environmental conditions and were not used to develop the indices (i.e., Minimally Degraded, Mixed, and Moderately Degraded). The Mixed category contains samples with insufficient water quality and stream habitat data. For this study, 1,866 Reference and 1,323 Degraded samples were identified and used to develop the order- and family-level versions of the Chesapeake-wide index, the Coast and Inland indices, and the twelve bioregion indices. Even fewer samples—1,587 Reference and 1,228 Degraded samples—were used to develop the genus-level version of the indices because we required a minimum of 90% of taxa reported in a sample to be identified to the genus-level during laboratory enumerations. 

## Index Construction

Results of the index construction comparisons (Appendix I) suggest that index development strategy has a minor influence on index CE. However, it has a major influence on the distributions of Reference and Degraded index scores and consequently on the thresholds for scoring metric values. None of the strategies consistently outperformed the others in terms of sensitivity or variability. This appears to be due in large part to a counter-balancing effect in the metric scoring process. For example, metrics in a Reference-quality sample that score low are typically countered by a larger number of metrics that score high, resulting in an overall high index score that often classifies the sample correctly as Reference-like. The key is to have sufficient numbers of sensitive metrics so the counter-balancing effect can occur. Our results suggest a minimum of five metrics is sufficient to achieve this counter-balancing effect.

Zero inflation influenced the distributions of Reference and Degraded index scores. Zero inflation occurs when abundance values for a given taxon are dominated by zeros, i.e. the taxon is rare (McCune et al. 2002). This effectively masks any underlying differences in abundance between Reference and Degraded conditions when the taxon occurs. Metric range, variability, and sensitivity criteria tended to protect against the zero inflation issue.
For the Chessie BIBI refinement, we used the index construction strategy that was most similar to strategies described in the literature (Method A in Appendix I). Multi-metric stream macroinvertebrate indices in the literature often include at least one metric in each of the five metric categories, which is thought to provide a holistic evaluation of the macroinvertebrate community. For the family- and genus-level indices in this study, we first ensured that four of the five metric categories were represented by their most sensitive metric. Additional metrics were then added without regard to category if they improved the index’s overall CE. For order-level indices, the most sensitive metric in each of the richness/diversity, composition, and tolerance categories were ensured, and additional metrics were included if they improved CE. Functional feeding group (FFG), habit, and some tolerance metrics are inappropriate to use at the order-level.

Composition, richness/diversity, and tolerance metrics generally had the highest discrimination efficiencies, reflecting strong responses to degradation. Habit and FFG metrics often had the lowest discrimination efficiencies, but in some instances, they could improve index CE by surprising amounts when included in the indices. Family- and genus-level versions of the region and bioregion indices generally contained more than ten metrics. Order-level indices generally contained fewer metrics, ranging from three metrics (PIED) to eight (SRV). 
