---
title: "Narrative Ratings"
output: html_notebook
---

## Narrative Ratings

We compared this study’s bioregion family-level Chessie BIBI ratings to the family-level ratings produced by Buchanan et al. (2011) to see how the multiple changes in methodology affected ratings of individual samples. Buchanan et al. (2011) worked with 487 Reference sampling events assigned to five inland bioregions compared to the 1,803 Reference sampling events assigned to ten inland bioregions in this study. They did not develop a Coast index, but instead used the existing Coastal Plain Macroinvertebrate Index (CPMI) developed by Maxted et al. (2000). Their water quality and stream habitat criteria for inland Reference and Degraded conditions were slightly different. Metrics in the current study were scored on a somewhat wider gradient, and CEs were determined with each index’s calculated BSP rather than an assumed BSP of 50. Thresholds for narrative ratings in the 2011 report were determined using averages of the five inland bioregions’ 50th, 25th, 10th, and 5th percentiles of Reference index scores. Thresholds in this study were determined for each individual bioregion and region with the Reference 50th, 25th, and 10th percentiles, and a value representing half of the 10th Reference percentile.

Using sample event ID, the 2011 family-level index ratings were paired with the corresponding family-level bioregion and region index ratings produced in this study. The twelve family-level bioregion indices compare well with the 2011 ratings (Table 18A). For the ten Inland bioregions, 84.6% of the ratings matched exactly or differed by only one rating (match = 47.2%, near = 37.4%). For the two Coast bioregions, 85.8% matched exactly or differed by only one rating (match = 50.2%, near = 35.6%). Just 15.4% of the Inland and 14.2% of the Coast ratings disagreed (differed by more than one rating on the 5-ratings scale). When the Inland ratings disagreed, this study’s ratings tended to be somewhat better. When the Coast ratings disagreed, this study’s ratings tended to be somewhat poorer.

The family-level region index ratings were also similar to the 2011 ratings (Table 18B). The Inland index ratings matched exactly or differed by only one rating 89.4% of the sampling events (match = 58.0%, near = 31.4%). For the Coast index, 93.2% of the ratings matched exactly or differed by one rating (match = 53.4%, near = 39.8%). Just 10.6% of the Inland and 6.8% of the Coast ratings disagreed by more than one rating.

_Table 18. Comparison of narrative ratings for sampling events used in Buchanan et al. (2011). The 2011 ratings were determined with methods described in Buchanan et al. (2011). This study’s ratings were determined with the methodology described above. Ratings that match exactly are highlighted in dark blue; those that differ by only one rating are highlighted in light blue._

Many habitat and water quality parameters used to classify Reference conditions correlate positively with %Forest and negatively with %Urban at the HUC12-level (Table L-4). We compared the narrative ratings of the family-level bioregion and family-level region indices to six land use categories along a disturbance gradient, to see if ratings corresponded to increasing anthropogenic impacts in their watersheds. Land use characteristics of the HUC12 watersheds (Retrieved [02/24/2017], from USEPA Recovery Potential Screening Tools, [https://www.epa.gov/rps/recovery-potential-screening-tools-downloadable-tools-comparing-watersheds](https://www.epa.gov/rps/recovery-potential-screening-tools-downloadable-tools-comparing-watersheds).) were grouped by their percentages of forest, urban, and agricultural area. The categories were: 1) >78%Forest + <5% Urban (least disturbed); 2) 50% - 78% Forest + <5% Urban (minimally disturbed); 3) Other; 4) <25% Forest + >50% Agriculture (disturbed); 5) <25% Forest + >20% Urban (disturbed); and 6) <25% Forest + >20% Urban + >50% Agriculture (most disturbed). The ratings of individual sample events were paired with their HUC12 watershed’s land use category. Table 19 shows the percentages of Excellent, Good, and Fair (EGF), as well as, Poor and Very Poor (PVP) ratings of the family-level indices in each of the six land use categories. Results for the bioregion indices are grouped by region for brevity. The largest percentages of Excellent, Good, and Fair ratings (EGF) occurred in the least disturbed watersheds; large percentages of Poor and Very Poor ratings (PVP) occurred in the most disturbed watersheds.

_Table 19. Narrative ratings of the bioregion and region versions of the family-level index in six different intensities of watershed disturbance. Percentages reflect the proportions of EGF (excellent, good, fair) and PVP (poor, very poor) ratings in each disturbance gradient category. For, forest; Urb, urban; Agr, agriculture; Other, land uses do not meet criteria of other disturbance gradient categories. *The bioregion index ratings are grouped by region for comparison purposes. Bolded, percentages greater than 60%._

We cross-compared the narrative ratings produced for two of the spatial indices (region, bioregion) and their three taxonomic versions (Table 20). Different versions of the index that show little disagreement (e.g., < 10%) can potentially be used together. Ratings were paired on sample event ID and the percentages of paired ratings that exactly match, nearly match (i.e., are adjacent ratings), and disagree (i.e., separated by one or more ratings) were determined. Family-level versions of the bioregion index (results are grouped by region) and the region index show the least overall disagreement, with 8.7% in the Coast region and 7.4% in the Inland region (Table 20A). Roughly half of the ratings matched exactly. The genus-level bioregion index (grouped by region) also showed little disagreement (7.2%) with the Inland genus-level index. Other comparisons of the region and bioregion taxonomic versions were not as strong. For taxonomic versions of the region index, the Inland family- and genus-level indices compared well, with only 9.7% disagreement (Table 20B). For taxonomic version of the bioregion index (grouped by region), Coast order- and family-level indices and Inland family- and genus-level indices compared well, with only 9.1% and 8.6% disagreement, respectively (Table 20C). The family-level versions of the bioregion index and the region index (separated into bioregions) showed less than 10% disagreement in eight of the twelve bioregions: SEP, CA, NRV, LNP, SRV, NCA, SGV, and PIED (Table 20D).

_Table 20. Cross-comparisons of ratings of the two spatial (i.e., region and bioregion) and three taxonomic (i.e., order-, family-, and genus-) versions of the index. Agreement: match, exact agreement (e.g., Fair and Fair); near, differ by one rating (e.g., Good and Fair); disagree, differ by more than one rating (e.g., Excellent and Fair). Highlighted cross-comparisons have 10% or fewer rating disagreements. Results are grouped by Coast and Inland regions in A – C; results are grouped by bioregion in D. A) Ratings produced by the three taxonomic versions of the two regional indices are compared by region to ratings produced by the three taxonomic versions of the twelve bioregion indices. B) Ratings produced by the genus-, family-, and order-level versions of the regional indices (Coast, Inland) are compared. C) Ratings produced by the genus-, family-, and order-level versions of the twelve bioregion indices are grouped by region for brevity and compared. D) Ratings produced by the family-level versions of the regional and bioregion indices are compared by bioregion._

